using Ways.Domain.Common;

namespace Ways.Domain.Articulos;

/// <summary>
/// Artículo del tenant (doc 10 §3): a diferencia de los padrones (<c>clientes</c>,
/// <c>proveedores</c>), NO usa el patrón <c>id_empresa</c> opcional — es tenant-wide, sin
/// columna <c>id_empresa</c> propia (decisión de producto 2026-08-02, doc 10 §3). Lo que
/// varía por empresa es la disponibilidad (<see cref="DisponibleParaTodas"/> +
/// <see cref="ArticuloEmpresa"/>), no la propiedad del dato.
///
/// Entidad dedicada (design decision 1): no reusa <c>ConfiguracionDeCatalogo&lt;T&gt;</c>/
/// <c>ServicioDeCatalogo&lt;T&gt;</c> — 14+ campos propios, junction de disponibilidad,
/// colección de códigos de barra, ninguno encaja en la base genérica de catálogos simples.
/// </summary>
public class Articulo : EntidadTenant
{
    public int Id { get; set; }

    /// <summary>Único por tenant (spec: codigo_interno Mandatory And Autogenerated) —
    /// supersede la marca <c>NULL</c>-able de doc 10: siempre tiene valor, asignado por
    /// <see cref="Application.Articulos.AsignadorDeCodigoInternoArticulo"/> cuando el llamador
    /// lo omite, u honrado tal cual cuando lo provee.</summary>
    public required string CodigoInterno { get; set; }

    public required string Nombre { get; set; }
    public string? Descripcion { get; set; }

    public int IdArea { get; set; }
    public int? IdCategoria { get; set; }
    public int? IdMarca { get; set; }
    public int? IdGrupo { get; set; }

    /// <summary>Proveedor de referencia para reposición — no exclusivo, no obliga que las
    /// compras vengan de él.</summary>
    public int? IdProveedorHabitual { get; set; }

    public int IdAlicuotaIva { get; set; }

    public UnidadVenta UnidadVenta { get; set; }
    public decimal? UnidadesPorBulto { get; set; }

    /// <summary><c>false</c> ⇒ servicio: no toca stock (doc 10 §3).</summary>
    public bool EsProducto { get; set; }

    public decimal? CostoLista { get; set; }
    public decimal? DescuentoProveedor { get; set; }

    /// <summary>Costo real de reposición — lo actualiza el flujo de compras (fuera de
    /// alcance de esta etapa).</summary>
    public decimal? CostoNominal { get; set; }

    /// <summary><c>true</c> (default) ⇒ visible en todas las empresas del tenant, incluidas
    /// las creadas después, sin backfill (spec: Availability Model). <c>false</c> ⇒ acotado a
    /// las empresas listadas en <see cref="ArticuloEmpresa"/>.</summary>
    public bool DisponibleParaTodas { get; set; } = true;

    public bool Activo { get; set; } = true;

    /// <summary>Etapa 12 (proposal decisión 1, gate §E): <c>true</c> ⇒ todo movimiento de stock
    /// de este artículo (venta, compra, transferencia, ajuste, conteo, decomiso, anulación)
    /// tiene que llevar un lote — el control efectivo también exige el parámetro de empresa
    /// <c>lotes_habilitado</c> (<c>ReglaDeLotes.ControlEfectivo</c>, slice 2). Tenant-wide,
    /// mismo criterio que <see cref="EsProducto"/>: un booleano en <c>articulos</c> que decide
    /// si un camino de código entero aplica, ya cargado por todo llamador que lo necesita.
    /// Default <c>false</c> — byte-idéntico al comportamiento de hoy para cualquier fila
    /// existente.</summary>
    public bool ControlaLote { get; set; }
}
