// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Ways.Domain.Organizacion;
using Ways.Domain.Usuarios;
using Ways.Infrastructure.Persistencia;

#nullable disable

namespace Ways.Infrastructure.Persistencia.Migraciones
{
    [DbContext(typeof(WaysDbContext))]
    [Migration("20260801154718_UsuariosMultiTenant")]
    partial class UsuariosMultiTenant
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "estado_tenant", new[] { "activo", "baja", "suspendido" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "estado_usuario", new[] { "activo", "bloqueado", "inactivo" });
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "citext");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.DataProtection.EntityFrameworkCore.DataProtectionKey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FriendlyName")
                        .HasColumnType("text");

                    b.Property<string>("Xml")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("DataProtectionKeys");
                });

            modelBuilder.Entity("Ways.Domain.Organizacion.Empresa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_empresa");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Cuit")
                        .HasMaxLength(13)
                        .HasColumnType("character varying(13)")
                        .HasColumnName("cuit");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<int>("IdTenant")
                        .HasColumnType("integer")
                        .HasColumnName("id_tenant");

                    b.Property<string>("NombreFantasia")
                        .HasMaxLength(150)
                        .HasColumnType("citext")
                        .HasColumnName("nombre_fantasia");

                    b.Property<string>("RazonSocial")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("citext")
                        .HasColumnName("razon_social");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasAlternateKey("Id", "IdTenant")
                        .HasName("ak_empresas_id_empresa_id_tenant");

                    b.HasIndex("IdTenant")
                        .HasDatabaseName("ix_empresas_tenant");

                    b.ToTable("empresas", (string)null);
                });

            modelBuilder.Entity("Ways.Domain.Organizacion.PuntoVenta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_punto_venta");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Domicilio")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("domicilio");

                    b.Property<string>("Facebook")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("facebook");

                    b.Property<string>("Horario")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("horario");

                    b.Property<int>("IdEmpresa")
                        .HasColumnType("integer")
                        .HasColumnName("id_empresa");

                    b.Property<int>("IdTenant")
                        .HasColumnType("integer")
                        .HasColumnName("id_tenant");

                    b.Property<string>("Instagram")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("instagram");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("citext")
                        .HasColumnName("nombre");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Web")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("web");

                    b.Property<string>("Whatsapp")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("whatsapp");

                    b.HasKey("Id");

                    b.HasAlternateKey("Id", "IdTenant")
                        .HasName("ak_puntos_venta_id_punto_venta_id_tenant");

                    b.HasIndex("IdTenant")
                        .HasDatabaseName("ix_puntos_venta_tenant");

                    b.HasIndex("IdEmpresa", "IdTenant")
                        .HasDatabaseName("ix_puntos_venta_empresa");

                    b.ToTable("puntos_venta", (string)null);
                });

            modelBuilder.Entity("Ways.Domain.Organizacion.Tenant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_tenant");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<EstadoTenant>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("estado_tenant")
                        .HasDefaultValue(EstadoTenant.Activo)
                        .HasColumnName("estado");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("citext")
                        .HasColumnName("nombre");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("tenants", (string)null);
                });

            modelBuilder.Entity("Ways.Domain.Usuarios.Rol", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id_rol");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("descripcion");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("citext")
                        .HasColumnName("nombre");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique()
                        .HasDatabaseName("ux_roles_nombre")
                        .HasFilter("deleted_at IS NULL");

                    b.ToTable("roles", (string)null);
                });

            modelBuilder.Entity("Ways.Domain.Usuarios.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_usuario");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<EstadoUsuario>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("estado_usuario")
                        .HasDefaultValue(EstadoUsuario.Activo)
                        .HasColumnName("estado");

                    b.Property<int?>("IdTenant")
                        .HasColumnType("integer")
                        .HasColumnName("id_tenant");

                    b.Property<short>("IntentosFallidos")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)0)
                        .HasColumnName("intentos_fallidos");

                    b.Property<string>("Mail")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("citext")
                        .HasColumnName("mail");

                    b.Property<string>("NombreUsuario")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("citext")
                        .HasColumnName("usuario");

                    b.Property<DateTimeOffset>("PasswordActualizadoEl")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("password_actualizado_el");

                    b.Property<string>("PasswordAlgoritmo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("password_algoritmo");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("password_hash");

                    b.Property<int>("RolId")
                        .HasColumnType("integer")
                        .HasColumnName("id_rol");

                    b.Property<DateTimeOffset?>("UltimaConexion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ultima_conexion");

                    b.Property<DateTimeOffset?>("UltimoIntentoFallido")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ultimo_intento_fallido");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("IdTenant")
                        .HasDatabaseName("ix_usuarios_tenant");

                    b.HasIndex("Mail")
                        .IsUnique()
                        .HasDatabaseName("ux_usuarios_mail")
                        .HasFilter("deleted_at IS NULL");

                    b.HasIndex("RolId")
                        .HasDatabaseName("ix_usuarios_rol");

                    b.HasIndex("IdTenant", "NombreUsuario")
                        .IsUnique()
                        .HasDatabaseName("ux_usuarios_usuario")
                        .HasFilter("deleted_at IS NULL");

                    NpgsqlIndexBuilderExtensions.AreNullsDistinct(b.HasIndex("IdTenant", "NombreUsuario"), false);

                    b.ToTable("usuarios", (string)null);
                });

            modelBuilder.Entity("Ways.Domain.Organizacion.Empresa", b =>
                {
                    b.HasOne("Ways.Domain.Organizacion.Tenant", null)
                        .WithMany()
                        .HasForeignKey("IdTenant")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_empresas_tenant");
                });

            modelBuilder.Entity("Ways.Domain.Organizacion.PuntoVenta", b =>
                {
                    b.HasOne("Ways.Domain.Organizacion.Empresa", null)
                        .WithMany()
                        .HasForeignKey("IdEmpresa", "IdTenant")
                        .HasPrincipalKey("Id", "IdTenant")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_puntos_venta_empresa");
                });

            modelBuilder.Entity("Ways.Domain.Usuarios.Usuario", b =>
                {
                    b.HasOne("Ways.Domain.Organizacion.Tenant", null)
                        .WithMany()
                        .HasForeignKey("IdTenant")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_usuarios_tenant");

                    b.HasOne("Ways.Domain.Usuarios.Rol", "Rol")
                        .WithMany("Usuarios")
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_usuarios_rol");

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("Ways.Domain.Usuarios.Rol", b =>
                {
                    b.Navigation("Usuarios");
                });
#pragma warning restore 612, 618
        }
    }
}
