// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Ways.Domain.Articulos;
using Ways.Domain.Catalogos;
using Ways.Domain.Clientes;
using Ways.Domain.Organizacion;
using Ways.Domain.Usuarios;
using Ways.Infrastructure.Persistencia;

#nullable disable

namespace Ways.Infrastructure.Persistencia.Migraciones
{
    [DbContext(typeof(WaysDbContext))]
    [Migration("20260803032131_PreciosVentanaValida")]
    partial class PreciosVentanaValida
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "clase_comprobante", new[] { "compra", "venta" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "comportamiento_medio_pago", new[] { "cuenta_corriente", "efectivo", "electronico" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "estado_tenant", new[] { "activo", "baja", "suspendido" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "estado_usuario", new[] { "activo", "bloqueado", "inactivo" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "modo_lista", new[] { "derivada", "fija" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "tipo_documento", new[] { "cuil", "cuit", "dni", "otro", "pasaporte" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "unidad_venta", new[] { "peso", "unidad" });
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "citext");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.DataProtection.EntityFrameworkCore.DataProtectionKey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FriendlyName")
                        .HasColumnType("text");

                    b.Property<string>("Xml")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("DataProtectionKeys");
                });

            modelBuilder.Entity("Ways.Domain.Articulos.Articulo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_articulo");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("activo");

                    b.Property<string>("CodigoInterno")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("citext")
                        .HasColumnName("codigo_interno");

                    b.Property<decimal?>("CostoLista")
                        .HasColumnType("numeric(14,2)")
                        .HasColumnName("costo_lista");

                    b.Property<decimal?>("CostoNominal")
                        .HasColumnType("numeric(14,2)")
                        .HasColumnName("costo_nominal");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Descripcion")
                        .HasColumnType("text")
                        .HasColumnName("descripcion");

                    b.Property<decimal?>("DescuentoProveedor")
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("descuento_proveedor");

                    b.Property<bool>("DisponibleParaTodas")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("disponible_para_todas");

                    b.Property<bool>("EsProducto")
                        .HasColumnType("boolean")
                        .HasColumnName("es_producto");

                    b.Property<int>("IdAlicuotaIva")
                        .HasColumnType("integer")
                        .HasColumnName("id_alicuota_iva");

                    b.Property<int>("IdArea")
                        .HasColumnType("integer")
                        .HasColumnName("id_area");

                    b.Property<int?>("IdCategoria")
                        .HasColumnType("integer")
                        .HasColumnName("id_categoria");

                    b.Property<int?>("IdGrupo")
                        .HasColumnType("integer")
                        .HasColumnName("id_grupo");

                    b.Property<int?>("IdMarca")
                        .HasColumnType("integer")
                        .HasColumnName("id_marca");

                    b.Property<int?>("IdProveedorHabitual")
                        .HasColumnType("integer")
                        .HasColumnName("id_proveedor_habitual");

                    b.Property<int>("IdTenant")
                        .HasColumnType("integer")
                        .HasColumnName("id_tenant");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("citext")
                        .HasColumnName("nombre");

                    b.Property<UnidadVenta>("UnidadVenta")
                        .HasColumnType("unidad_venta")
                        .HasColumnName("unidad_venta");

                    b.Property<decimal?>("UnidadesPorBulto")
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("unidades_por_bulto");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasAlternateKey("Id", "IdTenant")
                        .HasName("ak_articulos_id_articulo_id_tenant");

                    b.HasIndex("IdAlicuotaIva")
                        .HasDatabaseName("ix_articulos_alicuota_iva");

                    b.HasIndex("IdTenant")
                        .HasDatabaseName("ix_articulos_tenant");

                    b.HasIndex("IdArea", "IdTenant")
                        .HasDatabaseName("ix_articulos_area");

                    b.HasIndex("IdCategoria", "IdTenant")
                        .HasDatabaseName("ix_articulos_categoria");

                    b.HasIndex("IdGrupo", "IdTenant")
                        .HasDatabaseName("ix_articulos_grupo");

                    b.HasIndex("IdMarca", "IdTenant")
                        .HasDatabaseName("ix_articulos_marca");

                    b.HasIndex("IdProveedorHabitual", "IdTenant")
                        .HasDatabaseName("ix_articulos_proveedor_habitual");

                    b.HasIndex("IdTenant", "CodigoInterno")
                        .IsUnique()
                        .HasDatabaseName("ux_articulos_codigo_interno")
                        .HasFilter("deleted_at IS NULL");

                    b.ToTable("articulos", (string)null);
                });

            modelBuilder.Entity("Ways.Domain.Articulos.ArticuloEmpresa", b =>
                {
                    b.Property<int>("IdArticulo")
                        .HasColumnType("integer")
                        .HasColumnName("id_articulo");

                    b.Property<int>("IdEmpresa")
                        .HasColumnType("integer")
                        .HasColumnName("id_empresa");

                    b.Property<int>("IdTenant")
                        .HasColumnType("integer")
                        .HasColumnName("id_tenant");

                    b.HasKey("IdArticulo", "IdEmpresa");

                    b.HasIndex("IdTenant")
                        .HasDatabaseName("ix_articulos_empresas_tenant");

                    b.HasIndex("IdArticulo", "IdTenant")
                        .HasDatabaseName("ix_articulos_empresas_articulo");

                    b.HasIndex("IdEmpresa", "IdTenant")
                        .HasDatabaseName("ix_articulos_empresas_empresa");

                    b.ToTable("articulos_empresas", (string)null);
                });

            modelBuilder.Entity("Ways.Domain.Articulos.CodigoBarra", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_codigo_barra");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("activo");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("citext")
                        .HasColumnName("codigo");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<int>("IdArticulo")
                        .HasColumnType("integer")
                        .HasColumnName("id_articulo");

                    b.Property<int>("IdTenant")
                        .HasColumnType("integer")
                        .HasColumnName("id_tenant");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("IdTenant")
                        .HasDatabaseName("ix_codigos_barra_tenant");

                    b.HasIndex("Codigo", "IdTenant")
                        .IsUnique()
                        .HasDatabaseName("ux_codigos_barra_codigo_tenant")
                        .HasFilter("deleted_at IS NULL");

                    b.HasIndex("IdArticulo", "IdTenant")
                        .HasDatabaseName("ix_codigos_barra_articulo");

                    b.ToTable("codigos_barra", (string)null);
                });

            modelBuilder.Entity("Ways.Domain.Articulos.NumeracionArticulo", b =>
                {
                    b.Property<int>("IdTenant")
                        .HasColumnType("integer")
                        .HasColumnName("id_tenant");

                    b.Property<int>("ProximoNumero")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("proximo_numero");

                    b.HasKey("IdTenant");

                    b.ToTable("numeraciones_articulos", (string)null);
                });

            modelBuilder.Entity("Ways.Domain.Catalogos.AlicuotaIva", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_alicuota_iva");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("activo");

                    b.Property<short?>("CodigoAfip")
                        .HasColumnType("smallint")
                        .HasColumnName("codigo_afip");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("citext")
                        .HasColumnName("nombre");

                    b.Property<decimal>("Porcentaje")
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("porcentaje");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique()
                        .HasDatabaseName("ux_alicuotas_iva_nombre")
                        .HasFilter("deleted_at IS NULL");

                    b.ToTable("alicuotas_iva", (string)null);
                });

            modelBuilder.Entity("Ways.Domain.Catalogos.Area", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_area");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("activo");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<int?>("IdEmpresa")
                        .HasColumnType("integer")
                        .HasColumnName("id_empresa");

                    b.Property<int>("IdTenant")
                        .HasColumnType("integer")
                        .HasColumnName("id_tenant");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("citext")
                        .HasColumnName("nombre");

                    b.Property<int>("Orden")
                        .HasColumnType("integer")
                        .HasColumnName("orden");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasAlternateKey("Id", "IdTenant")
                        .HasName("ak_areas_id_area_id_tenant");

                    b.HasIndex("IdTenant")
                        .HasDatabaseName("ix_areas_tenant");

                    b.HasIndex("IdEmpresa", "IdTenant")
                        .HasDatabaseName("ix_areas_empresa");

                    b.HasIndex("IdTenant", "Nombre")
                        .IsUnique()
                        .HasDatabaseName("ux_areas_nombre_compartido")
                        .HasFilter("id_empresa IS NULL AND deleted_at IS NULL");

                    b.HasIndex("IdTenant", "IdEmpresa", "Nombre")
                        .IsUnique()
                        .HasDatabaseName("ux_areas_nombre_empresa")
                        .HasFilter("id_empresa IS NOT NULL AND deleted_at IS NULL");

                    b.ToTable("areas", (string)null);
                });

            modelBuilder.Entity("Ways.Domain.Catalogos.Categoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_categoria");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("activo");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<int?>("IdCategoriaPadre")
                        .HasColumnType("integer")
                        .HasColumnName("id_categoria_padre");

                    b.Property<int?>("IdEmpresa")
                        .HasColumnType("integer")
                        .HasColumnName("id_empresa");

                    b.Property<int>("IdTenant")
                        .HasColumnType("integer")
                        .HasColumnName("id_tenant");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("citext")
                        .HasColumnName("nombre");

                    b.Property<int>("Orden")
                        .HasColumnType("integer")
                        .HasColumnName("orden");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasAlternateKey("Id", "IdTenant")
                        .HasName("ak_categorias_id_categoria_id_tenant");

                    b.HasIndex("IdTenant")
                        .HasDatabaseName("ix_categorias_tenant");

                    b.HasIndex("IdCategoriaPadre", "IdTenant")
                        .HasDatabaseName("ix_categorias_padre");

                    b.HasIndex("IdEmpresa", "IdTenant")
                        .HasDatabaseName("ix_categorias_empresa");

                    b.HasIndex("IdTenant", "Nombre")
                        .IsUnique()
                        .HasDatabaseName("ux_categorias_nombre_compartido")
                        .HasFilter("id_empresa IS NULL AND deleted_at IS NULL");

                    b.HasIndex("IdTenant", "IdEmpresa", "Nombre")
                        .IsUnique()
                        .HasDatabaseName("ux_categorias_nombre_empresa")
                        .HasFilter("id_empresa IS NOT NULL AND deleted_at IS NULL");

                    b.ToTable("categorias", null, t =>
                        {
                            t.HasCheckConstraint("ck_categorias_padre_no_self", "id_categoria_padre IS DISTINCT FROM id_categoria");
                        });
                });

            modelBuilder.Entity("Ways.Domain.Catalogos.CondicionFiscal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_condicion_fiscal");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("activo");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("citext")
                        .HasColumnName("codigo");

                    b.Property<short?>("CodigoAfip")
                        .HasColumnType("smallint")
                        .HasColumnName("codigo_afip");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("citext")
                        .HasColumnName("nombre");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique()
                        .HasDatabaseName("ux_condiciones_fiscales_codigo")
                        .HasFilter("deleted_at IS NULL");

                    b.ToTable("condiciones_fiscales", (string)null);
                });

            modelBuilder.Entity("Ways.Domain.Catalogos.Grupo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_grupo");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("activo");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<int?>("IdEmpresa")
                        .HasColumnType("integer")
                        .HasColumnName("id_empresa");

                    b.Property<int>("IdTenant")
                        .HasColumnType("integer")
                        .HasColumnName("id_tenant");

                    b.Property<decimal?>("Margen")
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("margen");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("citext")
                        .HasColumnName("nombre");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasAlternateKey("Id", "IdTenant")
                        .HasName("ak_grupos_id_grupo_id_tenant");

                    b.HasIndex("IdTenant")
                        .HasDatabaseName("ix_grupos_tenant");

                    b.HasIndex("IdEmpresa", "IdTenant")
                        .HasDatabaseName("ix_grupos_empresa");

                    b.HasIndex("IdTenant", "Nombre")
                        .IsUnique()
                        .HasDatabaseName("ux_grupos_nombre_compartido")
                        .HasFilter("id_empresa IS NULL AND deleted_at IS NULL");

                    b.HasIndex("IdTenant", "IdEmpresa", "Nombre")
                        .IsUnique()
                        .HasDatabaseName("ux_grupos_nombre_empresa")
                        .HasFilter("id_empresa IS NOT NULL AND deleted_at IS NULL");

                    b.ToTable("grupos", (string)null);
                });

            modelBuilder.Entity("Ways.Domain.Catalogos.ListaPrecio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_lista_precio");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("activo");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<bool>("EsDefault")
                        .HasColumnType("boolean")
                        .HasColumnName("es_default");

                    b.Property<int?>("IdEmpresa")
                        .HasColumnType("integer")
                        .HasColumnName("id_empresa");

                    b.Property<int?>("IdListaBase")
                        .HasColumnType("integer")
                        .HasColumnName("id_lista_base");

                    b.Property<int>("IdTenant")
                        .HasColumnType("integer")
                        .HasColumnName("id_tenant");

                    b.Property<ModoLista>("Modo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("modo_lista")
                        .HasDefaultValue(ModoLista.Fija)
                        .HasColumnName("modo");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("citext")
                        .HasColumnName("nombre");

                    b.Property<decimal?>("Porcentaje")
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("porcentaje");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasAlternateKey("Id", "IdTenant")
                        .HasName("ak_listas_precio_id_lista_precio_id_tenant");

                    b.HasIndex("IdListaBase")
                        .HasDatabaseName("ix_listas_precio_lista_base");

                    b.HasIndex("IdTenant")
                        .HasDatabaseName("ix_listas_precio_tenant");

                    b.HasIndex("IdEmpresa", "IdTenant")
                        .HasDatabaseName("ix_listas_precio_empresa");

                    b.HasIndex("IdTenant", "EsDefault")
                        .IsUnique()
                        .HasDatabaseName("ux_listas_precio_default_compartido")
                        .HasFilter("id_empresa IS NULL AND deleted_at IS NULL AND es_default = true");

                    b.HasIndex("IdTenant", "Nombre")
                        .IsUnique()
                        .HasDatabaseName("ux_listas_precio_nombre_compartido")
                        .HasFilter("id_empresa IS NULL AND deleted_at IS NULL");

                    b.HasIndex("IdTenant", "IdEmpresa", "EsDefault")
                        .IsUnique()
                        .HasDatabaseName("ux_listas_precio_default_empresa")
                        .HasFilter("id_empresa IS NOT NULL AND deleted_at IS NULL AND es_default = true");

                    b.HasIndex("IdTenant", "IdEmpresa", "Nombre")
                        .IsUnique()
                        .HasDatabaseName("ux_listas_precio_nombre_empresa")
                        .HasFilter("id_empresa IS NOT NULL AND deleted_at IS NULL");

                    b.ToTable("listas_precio", (string)null);
                });

            modelBuilder.Entity("Ways.Domain.Catalogos.Marca", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_marca");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("activo");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<int?>("IdEmpresa")
                        .HasColumnType("integer")
                        .HasColumnName("id_empresa");

                    b.Property<int>("IdTenant")
                        .HasColumnType("integer")
                        .HasColumnName("id_tenant");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("citext")
                        .HasColumnName("nombre");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasAlternateKey("Id", "IdTenant")
                        .HasName("ak_marcas_id_marca_id_tenant");

                    b.HasIndex("IdTenant")
                        .HasDatabaseName("ix_marcas_tenant");

                    b.HasIndex("IdEmpresa", "IdTenant")
                        .HasDatabaseName("ix_marcas_empresa");

                    b.HasIndex("IdTenant", "Nombre")
                        .IsUnique()
                        .HasDatabaseName("ux_marcas_nombre_compartido")
                        .HasFilter("id_empresa IS NULL AND deleted_at IS NULL");

                    b.HasIndex("IdTenant", "IdEmpresa", "Nombre")
                        .IsUnique()
                        .HasDatabaseName("ux_marcas_nombre_empresa")
                        .HasFilter("id_empresa IS NOT NULL AND deleted_at IS NULL");

                    b.ToTable("marcas", (string)null);
                });

            modelBuilder.Entity("Ways.Domain.Catalogos.MedioPago", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_medio_pago");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("activo");

                    b.Property<bool>("AdmiteVuelto")
                        .HasColumnType("boolean")
                        .HasColumnName("admite_vuelto");

                    b.Property<ComportamientoMedioPago>("Comportamiento")
                        .HasColumnType("comportamiento_medio_pago")
                        .HasColumnName("comportamiento");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<int?>("IdEmpresa")
                        .HasColumnType("integer")
                        .HasColumnName("id_empresa");

                    b.Property<int>("IdTenant")
                        .HasColumnType("integer")
                        .HasColumnName("id_tenant");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("citext")
                        .HasColumnName("nombre");

                    b.Property<int>("Orden")
                        .HasColumnType("integer")
                        .HasColumnName("orden");

                    b.Property<decimal?>("RecargoPorcentaje")
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("recargo_porcentaje");

                    b.Property<bool>("RequiereReferencia")
                        .HasColumnType("boolean")
                        .HasColumnName("requiere_referencia");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("IdTenant")
                        .HasDatabaseName("ix_medios_pago_tenant");

                    b.HasIndex("IdEmpresa", "IdTenant")
                        .HasDatabaseName("ix_medios_pago_empresa");

                    b.HasIndex("IdTenant", "Nombre")
                        .IsUnique()
                        .HasDatabaseName("ux_medios_pago_nombre_compartido")
                        .HasFilter("id_empresa IS NULL AND deleted_at IS NULL");

                    b.HasIndex("IdTenant", "IdEmpresa", "Nombre")
                        .IsUnique()
                        .HasDatabaseName("ux_medios_pago_nombre_empresa")
                        .HasFilter("id_empresa IS NOT NULL AND deleted_at IS NULL");

                    b.ToTable("medios_pago", (string)null);
                });

            modelBuilder.Entity("Ways.Domain.Catalogos.Parametro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_parametro");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Clave")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("citext")
                        .HasColumnName("clave");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<int>("IdEmpresa")
                        .HasColumnType("integer")
                        .HasColumnName("id_empresa");

                    b.Property<int?>("IdPuntoVenta")
                        .HasColumnType("integer")
                        .HasColumnName("id_punto_venta");

                    b.Property<int>("IdTenant")
                        .HasColumnType("integer")
                        .HasColumnName("id_tenant");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Valor")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("valor");

                    b.HasKey("Id");

                    b.HasIndex("IdTenant")
                        .HasDatabaseName("ix_parametros_tenant");

                    b.HasIndex("IdEmpresa", "IdTenant")
                        .HasDatabaseName("ix_parametros_empresa");

                    b.HasIndex("IdPuntoVenta", "IdTenant")
                        .HasDatabaseName("ix_parametros_punto_venta");

                    b.HasIndex("IdTenant", "IdEmpresa", "Clave")
                        .IsUnique()
                        .HasDatabaseName("ux_parametros_empresa")
                        .HasFilter("id_punto_venta IS NULL AND deleted_at IS NULL");

                    b.HasIndex("IdTenant", "IdEmpresa", "IdPuntoVenta", "Clave")
                        .IsUnique()
                        .HasDatabaseName("ux_parametros_punto_venta")
                        .HasFilter("id_punto_venta IS NOT NULL AND deleted_at IS NULL");

                    b.ToTable("parametros", (string)null);
                });

            modelBuilder.Entity("Ways.Domain.Catalogos.TipoComprobante", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_tipo_comprobante");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("activo");

                    b.Property<bool>("AfectaStock")
                        .HasColumnType("boolean")
                        .HasColumnName("afecta_stock");

                    b.Property<ClaseComprobante>("Clase")
                        .HasColumnType("clase_comprobante")
                        .HasColumnName("clase");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("citext")
                        .HasColumnName("codigo");

                    b.Property<short?>("CodigoAfip")
                        .HasColumnType("smallint")
                        .HasColumnName("codigo_afip");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<bool>("DiscriminaIva")
                        .HasColumnType("boolean")
                        .HasColumnName("discrimina_iva");

                    b.Property<bool>("EsFiscal")
                        .HasColumnType("boolean")
                        .HasColumnName("es_fiscal");

                    b.Property<char?>("Letra")
                        .HasColumnType("char(1)")
                        .HasColumnName("letra");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("citext")
                        .HasColumnName("nombre");

                    b.Property<short>("Signo")
                        .HasColumnType("smallint")
                        .HasColumnName("signo");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique()
                        .HasDatabaseName("ux_tipos_comprobante_codigo")
                        .HasFilter("deleted_at IS NULL");

                    b.ToTable("tipos_comprobante", (string)null);
                });

            modelBuilder.Entity("Ways.Domain.Clientes.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_cliente");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("activo");

                    b.Property<string>("Apellido")
                        .HasMaxLength(150)
                        .HasColumnType("citext")
                        .HasColumnName("apellido");

                    b.Property<string>("Celular")
                        .HasMaxLength(50)
                        .HasColumnType("citext")
                        .HasColumnName("celular");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("CreditoIlimitado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("credito_ilimitado");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Domicilio")
                        .HasMaxLength(255)
                        .HasColumnType("citext")
                        .HasColumnName("domicilio");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("citext")
                        .HasColumnName("email");

                    b.Property<int>("IdCondicionFiscal")
                        .HasColumnType("integer")
                        .HasColumnName("id_condicion_fiscal");

                    b.Property<int?>("IdEmpresa")
                        .HasColumnType("integer")
                        .HasColumnName("id_empresa");

                    b.Property<int>("IdListaPrecio")
                        .HasColumnType("integer")
                        .HasColumnName("id_lista_precio");

                    b.Property<int>("IdTenant")
                        .HasColumnType("integer")
                        .HasColumnName("id_tenant");

                    b.Property<decimal>("LimiteCredito")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(14,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("limite_credito");

                    b.Property<DateOnly?>("Nacimiento")
                        .HasColumnType("date")
                        .HasColumnName("nacimiento");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("citext")
                        .HasColumnName("nombre");

                    b.Property<int>("Numero")
                        .HasColumnType("integer")
                        .HasColumnName("numero");

                    b.Property<string>("NumeroDocumento")
                        .HasMaxLength(30)
                        .HasColumnType("citext")
                        .HasColumnName("numero_documento");

                    b.Property<string>("Observaciones")
                        .HasColumnType("text")
                        .HasColumnName("observaciones");

                    b.Property<string>("RazonSocial")
                        .HasMaxLength(150)
                        .HasColumnType("citext")
                        .HasColumnName("razon_social");

                    b.Property<decimal>("Saldo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(14,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("saldo");

                    b.Property<string>("Telefono")
                        .HasMaxLength(50)
                        .HasColumnType("citext")
                        .HasColumnName("telefono");

                    b.Property<TipoDocumento?>("TipoDocumento")
                        .HasColumnType("tipo_documento")
                        .HasColumnName("tipo_documento");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("IdCondicionFiscal")
                        .HasDatabaseName("ix_clientes_condicion_fiscal");

                    b.HasIndex("IdTenant")
                        .HasDatabaseName("ix_clientes_tenant");

                    b.HasIndex("IdEmpresa", "IdTenant")
                        .HasDatabaseName("ix_clientes_empresa");

                    b.HasIndex("IdListaPrecio", "IdTenant")
                        .HasDatabaseName("ix_clientes_lista_precio");

                    b.HasIndex("IdTenant", "Numero")
                        .IsUnique()
                        .HasDatabaseName("ux_clientes_numero")
                        .HasFilter("deleted_at IS NULL");

                    b.ToTable("clientes", null, t =>
                        {
                            t.HasCheckConstraint("ck_clientes_cf_protegido", "numero <> 1 OR deleted_at IS NULL");
                        });
                });

            modelBuilder.Entity("Ways.Domain.Clientes.NumeracionCliente", b =>
                {
                    b.Property<int>("IdTenant")
                        .HasColumnType("integer")
                        .HasColumnName("id_tenant");

                    b.Property<int>("ProximoNumero")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("proximo_numero");

                    b.HasKey("IdTenant");

                    b.ToTable("numeraciones_clientes", (string)null);
                });

            modelBuilder.Entity("Ways.Domain.Organizacion.Empresa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_empresa");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Cuit")
                        .HasMaxLength(13)
                        .HasColumnType("character varying(13)")
                        .HasColumnName("cuit");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<int>("IdTenant")
                        .HasColumnType("integer")
                        .HasColumnName("id_tenant");

                    b.Property<string>("NombreFantasia")
                        .HasMaxLength(150)
                        .HasColumnType("citext")
                        .HasColumnName("nombre_fantasia");

                    b.Property<string>("RazonSocial")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("citext")
                        .HasColumnName("razon_social");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasAlternateKey("Id", "IdTenant")
                        .HasName("ak_empresas_id_empresa_id_tenant");

                    b.HasIndex("IdTenant")
                        .HasDatabaseName("ix_empresas_tenant");

                    b.ToTable("empresas", (string)null);
                });

            modelBuilder.Entity("Ways.Domain.Organizacion.PuntoVenta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_punto_venta");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Domicilio")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("domicilio");

                    b.Property<string>("Facebook")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("facebook");

                    b.Property<string>("Horario")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("horario");

                    b.Property<int>("IdEmpresa")
                        .HasColumnType("integer")
                        .HasColumnName("id_empresa");

                    b.Property<int>("IdTenant")
                        .HasColumnType("integer")
                        .HasColumnName("id_tenant");

                    b.Property<string>("Instagram")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("instagram");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("citext")
                        .HasColumnName("nombre");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Web")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("web");

                    b.Property<string>("Whatsapp")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("whatsapp");

                    b.HasKey("Id");

                    b.HasAlternateKey("Id", "IdTenant")
                        .HasName("ak_puntos_venta_id_punto_venta_id_tenant");

                    b.HasIndex("IdTenant")
                        .HasDatabaseName("ix_puntos_venta_tenant");

                    b.HasIndex("IdEmpresa", "IdTenant")
                        .HasDatabaseName("ix_puntos_venta_empresa");

                    b.ToTable("puntos_venta", (string)null);
                });

            modelBuilder.Entity("Ways.Domain.Organizacion.Tenant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_tenant");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<EstadoTenant>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("estado_tenant")
                        .HasDefaultValue(EstadoTenant.Activo)
                        .HasColumnName("estado");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("citext")
                        .HasColumnName("nombre");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("tenants", (string)null);
                });

            modelBuilder.Entity("Ways.Domain.Precios.Precio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_precio");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<int>("IdArticulo")
                        .HasColumnType("integer")
                        .HasColumnName("id_articulo");

                    b.Property<int>("IdListaPrecio")
                        .HasColumnType("integer")
                        .HasColumnName("id_lista_precio");

                    b.Property<int>("IdTenant")
                        .HasColumnType("integer")
                        .HasColumnName("id_tenant");

                    b.Property<decimal>("Monto")
                        .HasColumnType("numeric(14,2)")
                        .HasColumnName("precio");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<DateTimeOffset>("VigenteDesde")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("vigente_desde");

                    b.Property<DateTimeOffset?>("VigenteHasta")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("vigente_hasta");

                    b.HasKey("Id");

                    b.HasIndex("IdTenant")
                        .HasDatabaseName("ix_precios_tenant");

                    b.HasIndex("IdArticulo", "IdListaPrecio")
                        .IsUnique()
                        .HasDatabaseName("ux_precios_vigente")
                        .HasFilter("vigente_hasta IS NULL AND deleted_at IS NULL");

                    b.HasIndex("IdArticulo", "IdTenant")
                        .HasDatabaseName("ix_precios_articulo");

                    b.HasIndex("IdListaPrecio", "IdTenant")
                        .HasDatabaseName("ix_precios_lista_precio");

                    b.HasIndex("IdArticulo", "IdListaPrecio", "VigenteDesde")
                        .HasDatabaseName("ix_precios_vigencia");

                    b.ToTable("precios", null, t =>
                        {
                            t.HasCheckConstraint("ck_precios_ventana_valida", "vigente_hasta IS NULL OR vigente_hasta >= vigente_desde");
                        });
                });

            modelBuilder.Entity("Ways.Domain.Proveedores.Proveedor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_proveedor");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("activo");

                    b.Property<string>("CelularSupervisor")
                        .HasMaxLength(50)
                        .HasColumnType("citext")
                        .HasColumnName("celular_supervisor");

                    b.Property<string>("CelularVendedor")
                        .HasMaxLength(50)
                        .HasColumnType("citext")
                        .HasColumnName("celular_vendedor");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Cuit")
                        .HasMaxLength(13)
                        .HasColumnType("character varying(13)")
                        .HasColumnName("cuit");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Domicilio")
                        .HasMaxLength(255)
                        .HasColumnType("citext")
                        .HasColumnName("domicilio");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("citext")
                        .HasColumnName("email");

                    b.Property<int>("IdCondicionFiscal")
                        .HasColumnType("integer")
                        .HasColumnName("id_condicion_fiscal");

                    b.Property<int?>("IdEmpresa")
                        .HasColumnType("integer")
                        .HasColumnName("id_empresa");

                    b.Property<int>("IdTenant")
                        .HasColumnType("integer")
                        .HasColumnName("id_tenant");

                    b.Property<decimal?>("Margen")
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("margen");

                    b.Property<string>("NombreFantasia")
                        .HasMaxLength(150)
                        .HasColumnType("citext")
                        .HasColumnName("nombre_fantasia");

                    b.Property<string>("Observaciones")
                        .HasColumnType("text")
                        .HasColumnName("observaciones");

                    b.Property<string>("RazonSocial")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("citext")
                        .HasColumnName("razon_social");

                    b.Property<string>("Supervisor")
                        .HasMaxLength(150)
                        .HasColumnType("citext")
                        .HasColumnName("supervisor");

                    b.Property<string>("Telefono")
                        .HasMaxLength(50)
                        .HasColumnType("citext")
                        .HasColumnName("telefono");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Vendedor")
                        .HasMaxLength(150)
                        .HasColumnType("citext")
                        .HasColumnName("vendedor");

                    b.HasKey("Id");

                    b.HasAlternateKey("Id", "IdTenant")
                        .HasName("ak_proveedores_id_proveedor_id_tenant");

                    b.HasIndex("IdCondicionFiscal")
                        .HasDatabaseName("ix_proveedores_condicion_fiscal");

                    b.HasIndex("IdTenant")
                        .HasDatabaseName("ix_proveedores_tenant");

                    b.HasIndex("IdEmpresa", "IdTenant")
                        .HasDatabaseName("ix_proveedores_empresa");

                    b.HasIndex("IdTenant", "Cuit")
                        .IsUnique()
                        .HasDatabaseName("ux_proveedores_cuit")
                        .HasFilter("deleted_at IS NULL AND cuit IS NOT NULL");

                    b.ToTable("proveedores", (string)null);
                });

            modelBuilder.Entity("Ways.Domain.Usuarios.Rol", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id_rol");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("descripcion");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("citext")
                        .HasColumnName("nombre");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique()
                        .HasDatabaseName("ux_roles_nombre")
                        .HasFilter("deleted_at IS NULL");

                    b.ToTable("roles", (string)null);
                });

            modelBuilder.Entity("Ways.Domain.Usuarios.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_usuario");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<EstadoUsuario>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("estado_usuario")
                        .HasDefaultValue(EstadoUsuario.Activo)
                        .HasColumnName("estado");

                    b.Property<int?>("IdTenant")
                        .HasColumnType("integer")
                        .HasColumnName("id_tenant");

                    b.Property<short>("IntentosFallidos")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)0)
                        .HasColumnName("intentos_fallidos");

                    b.Property<string>("Mail")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("citext")
                        .HasColumnName("mail");

                    b.Property<string>("NombreUsuario")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("citext")
                        .HasColumnName("usuario");

                    b.Property<DateTimeOffset>("PasswordActualizadoEl")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("password_actualizado_el");

                    b.Property<string>("PasswordAlgoritmo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("password_algoritmo");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("password_hash");

                    b.Property<int>("RolId")
                        .HasColumnType("integer")
                        .HasColumnName("id_rol");

                    b.Property<DateTimeOffset?>("UltimaConexion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ultima_conexion");

                    b.Property<DateTimeOffset?>("UltimoIntentoFallido")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ultimo_intento_fallido");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("IdTenant")
                        .HasDatabaseName("ix_usuarios_tenant");

                    b.HasIndex("Mail")
                        .IsUnique()
                        .HasDatabaseName("ux_usuarios_mail")
                        .HasFilter("deleted_at IS NULL");

                    b.HasIndex("RolId")
                        .HasDatabaseName("ix_usuarios_rol");

                    b.HasIndex("IdTenant", "NombreUsuario")
                        .IsUnique()
                        .HasDatabaseName("ux_usuarios_usuario")
                        .HasFilter("deleted_at IS NULL");

                    NpgsqlIndexBuilderExtensions.AreNullsDistinct(b.HasIndex("IdTenant", "NombreUsuario"), false);

                    b.ToTable("usuarios", (string)null);
                });

            modelBuilder.Entity("Ways.Domain.Articulos.Articulo", b =>
                {
                    b.HasOne("Ways.Domain.Catalogos.AlicuotaIva", null)
                        .WithMany()
                        .HasForeignKey("IdAlicuotaIva")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_articulos_alicuota_iva");

                    b.HasOne("Ways.Domain.Organizacion.Tenant", null)
                        .WithMany()
                        .HasForeignKey("IdTenant")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_articulos_tenant");

                    b.HasOne("Ways.Domain.Catalogos.Area", null)
                        .WithMany()
                        .HasForeignKey("IdArea", "IdTenant")
                        .HasPrincipalKey("Id", "IdTenant")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_articulos_area");

                    b.HasOne("Ways.Domain.Catalogos.Categoria", null)
                        .WithMany()
                        .HasForeignKey("IdCategoria", "IdTenant")
                        .HasPrincipalKey("Id", "IdTenant")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_articulos_categoria");

                    b.HasOne("Ways.Domain.Catalogos.Grupo", null)
                        .WithMany()
                        .HasForeignKey("IdGrupo", "IdTenant")
                        .HasPrincipalKey("Id", "IdTenant")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_articulos_grupo");

                    b.HasOne("Ways.Domain.Catalogos.Marca", null)
                        .WithMany()
                        .HasForeignKey("IdMarca", "IdTenant")
                        .HasPrincipalKey("Id", "IdTenant")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_articulos_marca");

                    b.HasOne("Ways.Domain.Proveedores.Proveedor", null)
                        .WithMany()
                        .HasForeignKey("IdProveedorHabitual", "IdTenant")
                        .HasPrincipalKey("Id", "IdTenant")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_articulos_proveedor_habitual");
                });

            modelBuilder.Entity("Ways.Domain.Articulos.ArticuloEmpresa", b =>
                {
                    b.HasOne("Ways.Domain.Organizacion.Tenant", null)
                        .WithMany()
                        .HasForeignKey("IdTenant")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_articulos_empresas_tenant");

                    b.HasOne("Ways.Domain.Articulos.Articulo", null)
                        .WithMany()
                        .HasForeignKey("IdArticulo", "IdTenant")
                        .HasPrincipalKey("Id", "IdTenant")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_articulos_empresas_articulo");

                    b.HasOne("Ways.Domain.Organizacion.Empresa", null)
                        .WithMany()
                        .HasForeignKey("IdEmpresa", "IdTenant")
                        .HasPrincipalKey("Id", "IdTenant")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_articulos_empresas_empresa");
                });

            modelBuilder.Entity("Ways.Domain.Articulos.CodigoBarra", b =>
                {
                    b.HasOne("Ways.Domain.Organizacion.Tenant", null)
                        .WithMany()
                        .HasForeignKey("IdTenant")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_codigos_barra_tenant");

                    b.HasOne("Ways.Domain.Articulos.Articulo", null)
                        .WithMany()
                        .HasForeignKey("IdArticulo", "IdTenant")
                        .HasPrincipalKey("Id", "IdTenant")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_codigos_barra_articulo");
                });

            modelBuilder.Entity("Ways.Domain.Articulos.NumeracionArticulo", b =>
                {
                    b.HasOne("Ways.Domain.Organizacion.Tenant", null)
                        .WithMany()
                        .HasForeignKey("IdTenant")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_numeraciones_articulos_tenant");
                });

            modelBuilder.Entity("Ways.Domain.Catalogos.Area", b =>
                {
                    b.HasOne("Ways.Domain.Organizacion.Tenant", null)
                        .WithMany()
                        .HasForeignKey("IdTenant")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_areas_tenant");

                    b.HasOne("Ways.Domain.Organizacion.Empresa", null)
                        .WithMany()
                        .HasForeignKey("IdEmpresa", "IdTenant")
                        .HasPrincipalKey("Id", "IdTenant")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_areas_empresa");
                });

            modelBuilder.Entity("Ways.Domain.Catalogos.Categoria", b =>
                {
                    b.HasOne("Ways.Domain.Organizacion.Tenant", null)
                        .WithMany()
                        .HasForeignKey("IdTenant")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_categorias_tenant");

                    b.HasOne("Ways.Domain.Catalogos.Categoria", null)
                        .WithMany()
                        .HasForeignKey("IdCategoriaPadre", "IdTenant")
                        .HasPrincipalKey("Id", "IdTenant")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_categorias_padre");

                    b.HasOne("Ways.Domain.Organizacion.Empresa", null)
                        .WithMany()
                        .HasForeignKey("IdEmpresa", "IdTenant")
                        .HasPrincipalKey("Id", "IdTenant")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_categorias_empresa");
                });

            modelBuilder.Entity("Ways.Domain.Catalogos.Grupo", b =>
                {
                    b.HasOne("Ways.Domain.Organizacion.Tenant", null)
                        .WithMany()
                        .HasForeignKey("IdTenant")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_grupos_tenant");

                    b.HasOne("Ways.Domain.Organizacion.Empresa", null)
                        .WithMany()
                        .HasForeignKey("IdEmpresa", "IdTenant")
                        .HasPrincipalKey("Id", "IdTenant")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_grupos_empresa");
                });

            modelBuilder.Entity("Ways.Domain.Catalogos.ListaPrecio", b =>
                {
                    b.HasOne("Ways.Domain.Catalogos.ListaPrecio", null)
                        .WithMany()
                        .HasForeignKey("IdListaBase")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_listas_precio_lista_base");

                    b.HasOne("Ways.Domain.Organizacion.Tenant", null)
                        .WithMany()
                        .HasForeignKey("IdTenant")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_listas_precio_tenant");

                    b.HasOne("Ways.Domain.Organizacion.Empresa", null)
                        .WithMany()
                        .HasForeignKey("IdEmpresa", "IdTenant")
                        .HasPrincipalKey("Id", "IdTenant")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_listas_precio_empresa");
                });

            modelBuilder.Entity("Ways.Domain.Catalogos.Marca", b =>
                {
                    b.HasOne("Ways.Domain.Organizacion.Tenant", null)
                        .WithMany()
                        .HasForeignKey("IdTenant")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_marcas_tenant");

                    b.HasOne("Ways.Domain.Organizacion.Empresa", null)
                        .WithMany()
                        .HasForeignKey("IdEmpresa", "IdTenant")
                        .HasPrincipalKey("Id", "IdTenant")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_marcas_empresa");
                });

            modelBuilder.Entity("Ways.Domain.Catalogos.MedioPago", b =>
                {
                    b.HasOne("Ways.Domain.Organizacion.Tenant", null)
                        .WithMany()
                        .HasForeignKey("IdTenant")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_medios_pago_tenant");

                    b.HasOne("Ways.Domain.Organizacion.Empresa", null)
                        .WithMany()
                        .HasForeignKey("IdEmpresa", "IdTenant")
                        .HasPrincipalKey("Id", "IdTenant")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_medios_pago_empresa");
                });

            modelBuilder.Entity("Ways.Domain.Catalogos.Parametro", b =>
                {
                    b.HasOne("Ways.Domain.Organizacion.Tenant", null)
                        .WithMany()
                        .HasForeignKey("IdTenant")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_parametros_tenant");

                    b.HasOne("Ways.Domain.Organizacion.Empresa", null)
                        .WithMany()
                        .HasForeignKey("IdEmpresa", "IdTenant")
                        .HasPrincipalKey("Id", "IdTenant")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_parametros_empresa");

                    b.HasOne("Ways.Domain.Organizacion.PuntoVenta", null)
                        .WithMany()
                        .HasForeignKey("IdPuntoVenta", "IdTenant")
                        .HasPrincipalKey("Id", "IdTenant")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_parametros_punto_venta");
                });

            modelBuilder.Entity("Ways.Domain.Clientes.Cliente", b =>
                {
                    b.HasOne("Ways.Domain.Catalogos.CondicionFiscal", null)
                        .WithMany()
                        .HasForeignKey("IdCondicionFiscal")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_clientes_condicion_fiscal");

                    b.HasOne("Ways.Domain.Organizacion.Tenant", null)
                        .WithMany()
                        .HasForeignKey("IdTenant")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_clientes_tenant");

                    b.HasOne("Ways.Domain.Organizacion.Empresa", null)
                        .WithMany()
                        .HasForeignKey("IdEmpresa", "IdTenant")
                        .HasPrincipalKey("Id", "IdTenant")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_clientes_empresa");

                    b.HasOne("Ways.Domain.Catalogos.ListaPrecio", null)
                        .WithMany()
                        .HasForeignKey("IdListaPrecio", "IdTenant")
                        .HasPrincipalKey("Id", "IdTenant")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_clientes_lista_precio");
                });

            modelBuilder.Entity("Ways.Domain.Clientes.NumeracionCliente", b =>
                {
                    b.HasOne("Ways.Domain.Organizacion.Tenant", null)
                        .WithMany()
                        .HasForeignKey("IdTenant")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_numeraciones_clientes_tenant");
                });

            modelBuilder.Entity("Ways.Domain.Organizacion.Empresa", b =>
                {
                    b.HasOne("Ways.Domain.Organizacion.Tenant", null)
                        .WithMany()
                        .HasForeignKey("IdTenant")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_empresas_tenant");
                });

            modelBuilder.Entity("Ways.Domain.Organizacion.PuntoVenta", b =>
                {
                    b.HasOne("Ways.Domain.Organizacion.Empresa", null)
                        .WithMany()
                        .HasForeignKey("IdEmpresa", "IdTenant")
                        .HasPrincipalKey("Id", "IdTenant")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_puntos_venta_empresa");
                });

            modelBuilder.Entity("Ways.Domain.Precios.Precio", b =>
                {
                    b.HasOne("Ways.Domain.Organizacion.Tenant", null)
                        .WithMany()
                        .HasForeignKey("IdTenant")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_precios_tenant");

                    b.HasOne("Ways.Domain.Articulos.Articulo", null)
                        .WithMany()
                        .HasForeignKey("IdArticulo", "IdTenant")
                        .HasPrincipalKey("Id", "IdTenant")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_precios_articulo");

                    b.HasOne("Ways.Domain.Catalogos.ListaPrecio", null)
                        .WithMany()
                        .HasForeignKey("IdListaPrecio", "IdTenant")
                        .HasPrincipalKey("Id", "IdTenant")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_precios_lista_precio");
                });

            modelBuilder.Entity("Ways.Domain.Proveedores.Proveedor", b =>
                {
                    b.HasOne("Ways.Domain.Catalogos.CondicionFiscal", null)
                        .WithMany()
                        .HasForeignKey("IdCondicionFiscal")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_proveedores_condicion_fiscal");

                    b.HasOne("Ways.Domain.Organizacion.Tenant", null)
                        .WithMany()
                        .HasForeignKey("IdTenant")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_proveedores_tenant");

                    b.HasOne("Ways.Domain.Organizacion.Empresa", null)
                        .WithMany()
                        .HasForeignKey("IdEmpresa", "IdTenant")
                        .HasPrincipalKey("Id", "IdTenant")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_proveedores_empresa");
                });

            modelBuilder.Entity("Ways.Domain.Usuarios.Usuario", b =>
                {
                    b.HasOne("Ways.Domain.Organizacion.Tenant", null)
                        .WithMany()
                        .HasForeignKey("IdTenant")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_usuarios_tenant");

                    b.HasOne("Ways.Domain.Usuarios.Rol", "Rol")
                        .WithMany("Usuarios")
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_usuarios_rol");

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("Ways.Domain.Usuarios.Rol", b =>
                {
                    b.Navigation("Usuarios");
                });
#pragma warning restore 612, 618
        }
    }
}
