// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Ways.Domain.Catalogos;
using Ways.Domain.Organizacion;
using Ways.Domain.Usuarios;
using Ways.Infrastructure.Persistencia;

#nullable disable

namespace Ways.Infrastructure.Persistencia.Migraciones
{
    [DbContext(typeof(WaysDbContext))]
    [Migration("20260801233937_CatalogosGlobales")]
    partial class CatalogosGlobales
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "clase_comprobante", new[] { "compra", "venta" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "comportamiento_medio_pago", new[] { "cuenta_corriente", "efectivo", "electronico" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "estado_tenant", new[] { "activo", "baja", "suspendido" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "estado_usuario", new[] { "activo", "bloqueado", "inactivo" });
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "citext");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.DataProtection.EntityFrameworkCore.DataProtectionKey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FriendlyName")
                        .HasColumnType("text");

                    b.Property<string>("Xml")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("DataProtectionKeys");
                });

            modelBuilder.Entity("Ways.Domain.Catalogos.AlicuotaIva", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_alicuota_iva");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("activo");

                    b.Property<short?>("CodigoAfip")
                        .HasColumnType("smallint")
                        .HasColumnName("codigo_afip");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("citext")
                        .HasColumnName("nombre");

                    b.Property<decimal>("Porcentaje")
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("porcentaje");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique()
                        .HasDatabaseName("ux_alicuotas_iva_nombre")
                        .HasFilter("deleted_at IS NULL");

                    b.ToTable("alicuotas_iva", (string)null);
                });

            modelBuilder.Entity("Ways.Domain.Catalogos.Area", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_area");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("activo");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<int?>("IdEmpresa")
                        .HasColumnType("integer")
                        .HasColumnName("id_empresa");

                    b.Property<int>("IdTenant")
                        .HasColumnType("integer")
                        .HasColumnName("id_tenant");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("citext")
                        .HasColumnName("nombre");

                    b.Property<int>("Orden")
                        .HasColumnType("integer")
                        .HasColumnName("orden");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("IdTenant")
                        .HasDatabaseName("ix_areas_tenant");

                    b.HasIndex("IdEmpresa", "IdTenant")
                        .HasDatabaseName("ix_areas_empresa");

                    b.HasIndex("IdTenant", "Nombre")
                        .IsUnique()
                        .HasDatabaseName("ux_areas_nombre_compartido")
                        .HasFilter("id_empresa IS NULL AND deleted_at IS NULL");

                    b.HasIndex("IdTenant", "IdEmpresa", "Nombre")
                        .IsUnique()
                        .HasDatabaseName("ux_areas_nombre_empresa")
                        .HasFilter("id_empresa IS NOT NULL AND deleted_at IS NULL");

                    b.ToTable("areas", (string)null);
                });

            modelBuilder.Entity("Ways.Domain.Catalogos.Categoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_categoria");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("activo");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<int?>("IdCategoriaPadre")
                        .HasColumnType("integer")
                        .HasColumnName("id_categoria_padre");

                    b.Property<int?>("IdEmpresa")
                        .HasColumnType("integer")
                        .HasColumnName("id_empresa");

                    b.Property<int>("IdTenant")
                        .HasColumnType("integer")
                        .HasColumnName("id_tenant");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("citext")
                        .HasColumnName("nombre");

                    b.Property<int>("Orden")
                        .HasColumnType("integer")
                        .HasColumnName("orden");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasAlternateKey("Id", "IdTenant")
                        .HasName("ak_categorias_id_categoria_id_tenant");

                    b.HasIndex("IdTenant")
                        .HasDatabaseName("ix_categorias_tenant");

                    b.HasIndex("IdCategoriaPadre", "IdTenant")
                        .HasDatabaseName("ix_categorias_padre");

                    b.HasIndex("IdEmpresa", "IdTenant")
                        .HasDatabaseName("ix_categorias_empresa");

                    b.HasIndex("IdTenant", "Nombre")
                        .IsUnique()
                        .HasDatabaseName("ux_categorias_nombre_compartido")
                        .HasFilter("id_empresa IS NULL AND deleted_at IS NULL");

                    b.HasIndex("IdTenant", "IdEmpresa", "Nombre")
                        .IsUnique()
                        .HasDatabaseName("ux_categorias_nombre_empresa")
                        .HasFilter("id_empresa IS NOT NULL AND deleted_at IS NULL");

                    b.ToTable("categorias", (string)null);
                });

            modelBuilder.Entity("Ways.Domain.Catalogos.CondicionFiscal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_condicion_fiscal");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("activo");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("citext")
                        .HasColumnName("codigo");

                    b.Property<short?>("CodigoAfip")
                        .HasColumnType("smallint")
                        .HasColumnName("codigo_afip");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("citext")
                        .HasColumnName("nombre");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique()
                        .HasDatabaseName("ux_condiciones_fiscales_codigo")
                        .HasFilter("deleted_at IS NULL");

                    b.ToTable("condiciones_fiscales", (string)null);
                });

            modelBuilder.Entity("Ways.Domain.Catalogos.Grupo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_grupo");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("activo");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<int?>("IdEmpresa")
                        .HasColumnType("integer")
                        .HasColumnName("id_empresa");

                    b.Property<int>("IdTenant")
                        .HasColumnType("integer")
                        .HasColumnName("id_tenant");

                    b.Property<decimal?>("Margen")
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("margen");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("citext")
                        .HasColumnName("nombre");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("IdTenant")
                        .HasDatabaseName("ix_grupos_tenant");

                    b.HasIndex("IdEmpresa", "IdTenant")
                        .HasDatabaseName("ix_grupos_empresa");

                    b.HasIndex("IdTenant", "Nombre")
                        .IsUnique()
                        .HasDatabaseName("ux_grupos_nombre_compartido")
                        .HasFilter("id_empresa IS NULL AND deleted_at IS NULL");

                    b.HasIndex("IdTenant", "IdEmpresa", "Nombre")
                        .IsUnique()
                        .HasDatabaseName("ux_grupos_nombre_empresa")
                        .HasFilter("id_empresa IS NOT NULL AND deleted_at IS NULL");

                    b.ToTable("grupos", (string)null);
                });

            modelBuilder.Entity("Ways.Domain.Catalogos.Marca", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_marca");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("activo");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<int?>("IdEmpresa")
                        .HasColumnType("integer")
                        .HasColumnName("id_empresa");

                    b.Property<int>("IdTenant")
                        .HasColumnType("integer")
                        .HasColumnName("id_tenant");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("citext")
                        .HasColumnName("nombre");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("IdTenant")
                        .HasDatabaseName("ix_marcas_tenant");

                    b.HasIndex("IdEmpresa", "IdTenant")
                        .HasDatabaseName("ix_marcas_empresa");

                    b.HasIndex("IdTenant", "Nombre")
                        .IsUnique()
                        .HasDatabaseName("ux_marcas_nombre_compartido")
                        .HasFilter("id_empresa IS NULL AND deleted_at IS NULL");

                    b.HasIndex("IdTenant", "IdEmpresa", "Nombre")
                        .IsUnique()
                        .HasDatabaseName("ux_marcas_nombre_empresa")
                        .HasFilter("id_empresa IS NOT NULL AND deleted_at IS NULL");

                    b.ToTable("marcas", (string)null);
                });

            modelBuilder.Entity("Ways.Domain.Catalogos.MedioPago", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_medio_pago");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("activo");

                    b.Property<bool>("AdmiteVuelto")
                        .HasColumnType("boolean")
                        .HasColumnName("admite_vuelto");

                    b.Property<ComportamientoMedioPago>("Comportamiento")
                        .HasColumnType("comportamiento_medio_pago")
                        .HasColumnName("comportamiento");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<int?>("IdEmpresa")
                        .HasColumnType("integer")
                        .HasColumnName("id_empresa");

                    b.Property<int>("IdTenant")
                        .HasColumnType("integer")
                        .HasColumnName("id_tenant");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("citext")
                        .HasColumnName("nombre");

                    b.Property<int>("Orden")
                        .HasColumnType("integer")
                        .HasColumnName("orden");

                    b.Property<decimal?>("RecargoPorcentaje")
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("recargo_porcentaje");

                    b.Property<bool>("RequiereReferencia")
                        .HasColumnType("boolean")
                        .HasColumnName("requiere_referencia");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("IdTenant")
                        .HasDatabaseName("ix_medios_pago_tenant");

                    b.HasIndex("IdEmpresa", "IdTenant")
                        .HasDatabaseName("ix_medios_pago_empresa");

                    b.HasIndex("IdTenant", "Nombre")
                        .IsUnique()
                        .HasDatabaseName("ux_medios_pago_nombre_compartido")
                        .HasFilter("id_empresa IS NULL AND deleted_at IS NULL");

                    b.HasIndex("IdTenant", "IdEmpresa", "Nombre")
                        .IsUnique()
                        .HasDatabaseName("ux_medios_pago_nombre_empresa")
                        .HasFilter("id_empresa IS NOT NULL AND deleted_at IS NULL");

                    b.ToTable("medios_pago", (string)null);
                });

            modelBuilder.Entity("Ways.Domain.Catalogos.TipoComprobante", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_tipo_comprobante");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("activo");

                    b.Property<bool>("AfectaStock")
                        .HasColumnType("boolean")
                        .HasColumnName("afecta_stock");

                    b.Property<ClaseComprobante>("Clase")
                        .HasColumnType("clase_comprobante")
                        .HasColumnName("clase");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("citext")
                        .HasColumnName("codigo");

                    b.Property<short?>("CodigoAfip")
                        .HasColumnType("smallint")
                        .HasColumnName("codigo_afip");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<bool>("DiscriminaIva")
                        .HasColumnType("boolean")
                        .HasColumnName("discrimina_iva");

                    b.Property<bool>("EsFiscal")
                        .HasColumnType("boolean")
                        .HasColumnName("es_fiscal");

                    b.Property<char?>("Letra")
                        .HasColumnType("char(1)")
                        .HasColumnName("letra");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("citext")
                        .HasColumnName("nombre");

                    b.Property<short>("Signo")
                        .HasColumnType("smallint")
                        .HasColumnName("signo");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique()
                        .HasDatabaseName("ux_tipos_comprobante_codigo")
                        .HasFilter("deleted_at IS NULL");

                    b.ToTable("tipos_comprobante", (string)null);
                });

            modelBuilder.Entity("Ways.Domain.Organizacion.Empresa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_empresa");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Cuit")
                        .HasMaxLength(13)
                        .HasColumnType("character varying(13)")
                        .HasColumnName("cuit");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<int>("IdTenant")
                        .HasColumnType("integer")
                        .HasColumnName("id_tenant");

                    b.Property<string>("NombreFantasia")
                        .HasMaxLength(150)
                        .HasColumnType("citext")
                        .HasColumnName("nombre_fantasia");

                    b.Property<string>("RazonSocial")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("citext")
                        .HasColumnName("razon_social");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasAlternateKey("Id", "IdTenant")
                        .HasName("ak_empresas_id_empresa_id_tenant");

                    b.HasIndex("IdTenant")
                        .HasDatabaseName("ix_empresas_tenant");

                    b.ToTable("empresas", (string)null);
                });

            modelBuilder.Entity("Ways.Domain.Organizacion.PuntoVenta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_punto_venta");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Domicilio")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("domicilio");

                    b.Property<string>("Facebook")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("facebook");

                    b.Property<string>("Horario")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("horario");

                    b.Property<int>("IdEmpresa")
                        .HasColumnType("integer")
                        .HasColumnName("id_empresa");

                    b.Property<int>("IdTenant")
                        .HasColumnType("integer")
                        .HasColumnName("id_tenant");

                    b.Property<string>("Instagram")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("instagram");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("citext")
                        .HasColumnName("nombre");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Web")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("web");

                    b.Property<string>("Whatsapp")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("whatsapp");

                    b.HasKey("Id");

                    b.HasAlternateKey("Id", "IdTenant")
                        .HasName("ak_puntos_venta_id_punto_venta_id_tenant");

                    b.HasIndex("IdTenant")
                        .HasDatabaseName("ix_puntos_venta_tenant");

                    b.HasIndex("IdEmpresa", "IdTenant")
                        .HasDatabaseName("ix_puntos_venta_empresa");

                    b.ToTable("puntos_venta", (string)null);
                });

            modelBuilder.Entity("Ways.Domain.Organizacion.Tenant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_tenant");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<EstadoTenant>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("estado_tenant")
                        .HasDefaultValue(EstadoTenant.Activo)
                        .HasColumnName("estado");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("citext")
                        .HasColumnName("nombre");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("tenants", (string)null);
                });

            modelBuilder.Entity("Ways.Domain.Usuarios.Rol", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id_rol");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("descripcion");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("citext")
                        .HasColumnName("nombre");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique()
                        .HasDatabaseName("ux_roles_nombre")
                        .HasFilter("deleted_at IS NULL");

                    b.ToTable("roles", (string)null);
                });

            modelBuilder.Entity("Ways.Domain.Usuarios.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_usuario");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<EstadoUsuario>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("estado_usuario")
                        .HasDefaultValue(EstadoUsuario.Activo)
                        .HasColumnName("estado");

                    b.Property<int?>("IdTenant")
                        .HasColumnType("integer")
                        .HasColumnName("id_tenant");

                    b.Property<short>("IntentosFallidos")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)0)
                        .HasColumnName("intentos_fallidos");

                    b.Property<string>("Mail")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("citext")
                        .HasColumnName("mail");

                    b.Property<string>("NombreUsuario")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("citext")
                        .HasColumnName("usuario");

                    b.Property<DateTimeOffset>("PasswordActualizadoEl")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("password_actualizado_el");

                    b.Property<string>("PasswordAlgoritmo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("password_algoritmo");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("password_hash");

                    b.Property<int>("RolId")
                        .HasColumnType("integer")
                        .HasColumnName("id_rol");

                    b.Property<DateTimeOffset?>("UltimaConexion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ultima_conexion");

                    b.Property<DateTimeOffset?>("UltimoIntentoFallido")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ultimo_intento_fallido");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("IdTenant")
                        .HasDatabaseName("ix_usuarios_tenant");

                    b.HasIndex("Mail")
                        .IsUnique()
                        .HasDatabaseName("ux_usuarios_mail")
                        .HasFilter("deleted_at IS NULL");

                    b.HasIndex("RolId")
                        .HasDatabaseName("ix_usuarios_rol");

                    b.HasIndex("IdTenant", "NombreUsuario")
                        .IsUnique()
                        .HasDatabaseName("ux_usuarios_usuario")
                        .HasFilter("deleted_at IS NULL");

                    NpgsqlIndexBuilderExtensions.AreNullsDistinct(b.HasIndex("IdTenant", "NombreUsuario"), false);

                    b.ToTable("usuarios", (string)null);
                });

            modelBuilder.Entity("Ways.Domain.Catalogos.Area", b =>
                {
                    b.HasOne("Ways.Domain.Organizacion.Tenant", null)
                        .WithMany()
                        .HasForeignKey("IdTenant")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_areas_tenant");

                    b.HasOne("Ways.Domain.Organizacion.Empresa", null)
                        .WithMany()
                        .HasForeignKey("IdEmpresa", "IdTenant")
                        .HasPrincipalKey("Id", "IdTenant")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_areas_empresa");
                });

            modelBuilder.Entity("Ways.Domain.Catalogos.Categoria", b =>
                {
                    b.HasOne("Ways.Domain.Organizacion.Tenant", null)
                        .WithMany()
                        .HasForeignKey("IdTenant")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_categorias_tenant");

                    b.HasOne("Ways.Domain.Catalogos.Categoria", null)
                        .WithMany()
                        .HasForeignKey("IdCategoriaPadre", "IdTenant")
                        .HasPrincipalKey("Id", "IdTenant")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_categorias_padre");

                    b.HasOne("Ways.Domain.Organizacion.Empresa", null)
                        .WithMany()
                        .HasForeignKey("IdEmpresa", "IdTenant")
                        .HasPrincipalKey("Id", "IdTenant")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_categorias_empresa");
                });

            modelBuilder.Entity("Ways.Domain.Catalogos.Grupo", b =>
                {
                    b.HasOne("Ways.Domain.Organizacion.Tenant", null)
                        .WithMany()
                        .HasForeignKey("IdTenant")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_grupos_tenant");

                    b.HasOne("Ways.Domain.Organizacion.Empresa", null)
                        .WithMany()
                        .HasForeignKey("IdEmpresa", "IdTenant")
                        .HasPrincipalKey("Id", "IdTenant")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_grupos_empresa");
                });

            modelBuilder.Entity("Ways.Domain.Catalogos.Marca", b =>
                {
                    b.HasOne("Ways.Domain.Organizacion.Tenant", null)
                        .WithMany()
                        .HasForeignKey("IdTenant")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_marcas_tenant");

                    b.HasOne("Ways.Domain.Organizacion.Empresa", null)
                        .WithMany()
                        .HasForeignKey("IdEmpresa", "IdTenant")
                        .HasPrincipalKey("Id", "IdTenant")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_marcas_empresa");
                });

            modelBuilder.Entity("Ways.Domain.Catalogos.MedioPago", b =>
                {
                    b.HasOne("Ways.Domain.Organizacion.Tenant", null)
                        .WithMany()
                        .HasForeignKey("IdTenant")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_medios_pago_tenant");

                    b.HasOne("Ways.Domain.Organizacion.Empresa", null)
                        .WithMany()
                        .HasForeignKey("IdEmpresa", "IdTenant")
                        .HasPrincipalKey("Id", "IdTenant")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_medios_pago_empresa");
                });

            modelBuilder.Entity("Ways.Domain.Organizacion.Empresa", b =>
                {
                    b.HasOne("Ways.Domain.Organizacion.Tenant", null)
                        .WithMany()
                        .HasForeignKey("IdTenant")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_empresas_tenant");
                });

            modelBuilder.Entity("Ways.Domain.Organizacion.PuntoVenta", b =>
                {
                    b.HasOne("Ways.Domain.Organizacion.Empresa", null)
                        .WithMany()
                        .HasForeignKey("IdEmpresa", "IdTenant")
                        .HasPrincipalKey("Id", "IdTenant")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_puntos_venta_empresa");
                });

            modelBuilder.Entity("Ways.Domain.Usuarios.Usuario", b =>
                {
                    b.HasOne("Ways.Domain.Organizacion.Tenant", null)
                        .WithMany()
                        .HasForeignKey("IdTenant")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_usuarios_tenant");

                    b.HasOne("Ways.Domain.Usuarios.Rol", "Rol")
                        .WithMany("Usuarios")
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_usuarios_rol");

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("Ways.Domain.Usuarios.Rol", b =>
                {
                    b.Navigation("Usuarios");
                });
#pragma warning restore 612, 618
        }
    }
}
