using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Ways.Domain.Articulos;
using Ways.Domain.Catalogos;
using Ways.Domain.Organizacion;
using Ways.Domain.Proveedores;

namespace Ways.Infrastructure.Persistencia.Configuraciones;

/// <summary>
/// Mapea <see cref="Articulo"/> (design decision 1, Table Shapes): entidad dedicada,
/// tenant-wide sin <c>id_empresa</c> — a diferencia de <c>ConfiguracionDeCatalogo&lt;T&gt;</c>,
/// no tiene dedupe por nombre ni alcance opcional a empresa.
/// </summary>
public class ArticuloConfiguration : IEntityTypeConfiguration<Articulo>
{
    public void Configure(EntityTypeBuilder<Articulo> builder)
    {
        builder.ToTable("articulos");

        builder.HasKey(a => a.Id);

        builder.Property(a => a.Id)
            .HasColumnName("id_articulo")
            .UseIdentityByDefaultColumn();

        builder.Property(a => a.IdTenant)
            .HasColumnName("id_tenant")
            .IsRequired();

        // Habilita las FKs compuestas de los dependientes (codigos_barra, articulos_empresas,
        // precios) — mismo patrón que Empresa/Categoria/ListaPrecio (ADR-9).
        builder.HasAlternateKey(a => new { a.Id, a.IdTenant })
            .HasName("ak_articulos_id_articulo_id_tenant");

        builder.Property(a => a.CodigoInterno)
            .HasColumnName("codigo_interno")
            .HasColumnType("citext")
            .HasMaxLength(30)
            .IsRequired();

        builder.Property(a => a.Nombre)
            .HasColumnName("nombre")
            .HasColumnType("citext")
            .HasMaxLength(150)
            .IsRequired();

        builder.Property(a => a.Descripcion)
            .HasColumnName("descripcion")
            .HasColumnType("text");

        builder.Property(a => a.IdArea).HasColumnName("id_area").IsRequired();
        builder.Property(a => a.IdCategoria).HasColumnName("id_categoria");
        builder.Property(a => a.IdMarca).HasColumnName("id_marca");
        builder.Property(a => a.IdGrupo).HasColumnName("id_grupo");
        builder.Property(a => a.IdProveedorHabitual).HasColumnName("id_proveedor_habitual");
        builder.Property(a => a.IdAlicuotaIva).HasColumnName("id_alicuota_iva").IsRequired();

        builder.Property(a => a.UnidadVenta)
            .HasColumnName("unidad_venta")
            .HasColumnType("unidad_venta")
            .IsRequired();

        builder.Property(a => a.UnidadesPorBulto)
            .HasColumnName("unidades_por_bulto")
            .HasColumnType("numeric(10,2)");

        builder.Property(a => a.EsProducto)
            .HasColumnName("es_producto")
            .IsRequired();

        builder.Property(a => a.CostoLista)
            .HasColumnName("costo_lista")
            .HasColumnType("numeric(14,2)");

        builder.Property(a => a.DescuentoProveedor)
            .HasColumnName("descuento_proveedor")
            .HasColumnType("numeric(5,2)");

        builder.Property(a => a.CostoNominal)
            .HasColumnName("costo_nominal")
            .HasColumnType("numeric(14,2)");

        builder.Property(a => a.DisponibleParaTodas)
            .HasColumnName("disponible_para_todas")
            .HasDefaultValue(true)
            .IsRequired();

        builder.Property(a => a.Activo)
            .HasColumnName("activo")
            .HasDefaultValue(true)
            .IsRequired();

        // Etapa 12 (proposal decisión 1, gate §E).
        builder.Property(a => a.ControlaLote)
            .HasColumnName("controla_lote")
            .HasDefaultValue(false)
            .IsRequired();

        builder.Property(a => a.CreatedAt).HasColumnName("created_at").IsRequired();
        builder.Property(a => a.UpdatedAt).HasColumnName("updated_at").IsRequired();
        builder.Property(a => a.DeletedAt).HasColumnName("deleted_at");

        builder.Ignore(a => a.EstaEliminada);

        // spec "codigo_interno Mandatory And Autogenerated": único por tenant, backstop del
        // pre-chequeo de ServicioDeArticulos (Slice 2) — bajo operación normal el chequeo
        // previo ya evita el choque, esto cubre la carrera.
        builder.HasIndex(a => new { a.IdTenant, a.CodigoInterno })
            .HasDatabaseName("ux_articulos_codigo_interno")
            .HasFilter("deleted_at IS NULL")
            .IsUnique();

        builder.HasIndex(a => a.IdTenant).HasDatabaseName("ix_articulos_tenant");

        // Etapa 12 (proposal decisión 1, gate §E): sirve tanto el conjunto de reconciliación
        // (ServicioDeLotes.ReconciliarAsync, slice 4) como el listado de artículos lot-effective.
        builder.HasIndex(a => a.IdTenant)
            .HasDatabaseName("ix_articulos_controla_lote")
            .HasFilter("controla_lote AND deleted_at IS NULL");

        // Nombres explícitos en snake_case (doc 10): sin esto EF nombra los índices de
        // soporte de cada FK con su convención propia (IX_articulos_id_area, PascalCase),
        // rompiendo la convención del resto del esquema — mismo fix que stage 2 aplicó antes
        // de generar su migración.
        builder.HasIndex(a => new { a.IdArea, a.IdTenant }).HasDatabaseName("ix_articulos_area");
        builder.HasIndex(a => new { a.IdCategoria, a.IdTenant }).HasDatabaseName("ix_articulos_categoria");
        builder.HasIndex(a => new { a.IdMarca, a.IdTenant }).HasDatabaseName("ix_articulos_marca");
        builder.HasIndex(a => new { a.IdGrupo, a.IdTenant }).HasDatabaseName("ix_articulos_grupo");
        builder.HasIndex(a => new { a.IdProveedorHabitual, a.IdTenant }).HasDatabaseName("ix_articulos_proveedor_habitual");
        builder.HasIndex(a => a.IdAlicuotaIva).HasDatabaseName("ix_articulos_alicuota_iva");

        builder.HasOne<Tenant>()
            .WithMany()
            .HasForeignKey(a => a.IdTenant)
            .HasConstraintName("fk_articulos_tenant")
            .OnDelete(DeleteBehavior.Restrict);

        // Composite FKs (design decision 7): un articulo del tenant 1 no puede referenciar el
        // area/categoria/marca/grupo/proveedor del tenant 2 ni por bug — antes de este gate,
        // area/marca/grupo/proveedores no tenían la clave alterna (Id, IdTenant) que esto
        // necesita; categorias ya la tenía (stage 2 hardening).
        builder.HasOne<Area>()
            .WithMany()
            .HasForeignKey(a => new { a.IdArea, a.IdTenant })
            .HasPrincipalKey(x => new { x.Id, x.IdTenant })
            .HasConstraintName("fk_articulos_area")
            .OnDelete(DeleteBehavior.Restrict);

        builder.HasOne<Categoria>()
            .WithMany()
            .HasForeignKey(a => new { a.IdCategoria, a.IdTenant })
            .HasPrincipalKey(x => new { x.Id, x.IdTenant })
            .HasConstraintName("fk_articulos_categoria")
            .OnDelete(DeleteBehavior.Restrict);

        builder.HasOne<Marca>()
            .WithMany()
            .HasForeignKey(a => new { a.IdMarca, a.IdTenant })
            .HasPrincipalKey(x => new { x.Id, x.IdTenant })
            .HasConstraintName("fk_articulos_marca")
            .OnDelete(DeleteBehavior.Restrict);

        builder.HasOne<Grupo>()
            .WithMany()
            .HasForeignKey(a => new { a.IdGrupo, a.IdTenant })
            .HasPrincipalKey(x => new { x.Id, x.IdTenant })
            .HasConstraintName("fk_articulos_grupo")
            .OnDelete(DeleteBehavior.Restrict);

        builder.HasOne<Proveedor>()
            .WithMany()
            .HasForeignKey(a => new { a.IdProveedorHabitual, a.IdTenant })
            .HasPrincipalKey(x => new { x.Id, x.IdTenant })
            .HasConstraintName("fk_articulos_proveedor_habitual")
            .OnDelete(DeleteBehavior.Restrict);

        // Simple (no compuesta): alicuotas_iva es un catálogo [global] sin id_tenant
        // (ADR-11, gate #4) — no hay tenant que cruzar.
        builder.HasOne<AlicuotaIva>()
            .WithMany()
            .HasForeignKey(a => a.IdAlicuotaIva)
            .HasConstraintName("fk_articulos_alicuota_iva")
            .OnDelete(DeleteBehavior.Restrict);
    }
}
