using Ways.Domain.Articulos;

namespace Ways.Application.Articulos;

/// <summary><see cref="IdsEmpresas"/> (judgment-day ronda 1, item 2) expone el subconjunto
/// ACTUAL de empresas del artículo — vacío cuando <see cref="DisponibleParaTodas"/> es
/// <c>true</c> — para que un cliente HTTP pueda armar un PUT de no-op (releer el detalle y
/// reenviarlo tal cual) sin perder el subset por mandar <c>null</c>. <c>ListarAsync</c> lo deja
/// vacío por fila (evita el N+1 de una query por artículo listado); el valor real solo se
/// completa en <c>ObtenerAsync</c>/<c>CrearAsync</c>/<c>ActualizarAsync</c>, que ya conocen o
/// resuelven el subset como parte de la operación.</summary>
public record ArticuloListado(
    int Id,
    string CodigoInterno,
    string Nombre,
    string? Descripcion,
    int IdArea,
    int? IdCategoria,
    int? IdMarca,
    int? IdGrupo,
    int? IdProveedorHabitual,
    int IdAlicuotaIva,
    UnidadVenta UnidadVenta,
    decimal? UnidadesPorBulto,
    bool EsProducto,
    decimal? CostoLista,
    decimal? DescuentoProveedor,
    decimal? CostoNominal,
    bool DisponibleParaTodas,
    IReadOnlyList<int> IdsEmpresas,
    bool Activo,
    bool ControlaLote);

/// <summary><see cref="CodigoInterno"/> es opcional a propósito (spec: codigo_interno
/// Mandatory And Autogenerated) — cuando se omite, <c>ServicioDeArticulos.CrearAsync</c> lo
/// asigna desde <see cref="AsignadorDeCodigoInternoArticulo"/>; cuando se provee, se valida
/// único por tenant antes del INSERT. <see cref="IdsEmpresas"/> solo se usa cuando
/// <see cref="DisponibleParaTodas"/> es <c>false</c> (spec: Availability Model,
/// articulos_empresas Junction Schema) — se ignora en caso contrario.</summary>
public record AltaArticulo(
    string? CodigoInterno,
    string Nombre,
    string? Descripcion,
    int IdArea,
    int? IdCategoria,
    int? IdMarca,
    int? IdGrupo,
    int? IdProveedorHabitual,
    int IdAlicuotaIva,
    UnidadVenta UnidadVenta,
    decimal? UnidadesPorBulto,
    bool EsProducto,
    decimal? CostoLista,
    decimal? DescuentoProveedor,
    decimal? CostoNominal,
    bool DisponibleParaTodas = true,
    IReadOnlyList<int>? IdsEmpresas = null,
    bool Activo = true,
    bool ControlaLote = false);

/// <summary><c>CodigoInterno</c> no aparece a propósito: no es editable por este ABM (mismo
/// criterio que <see cref="Ways.Application.Clientes.ClienteListado.Numero"/> — un valor
/// asignado en el alta, nunca tocado por una edición posterior). <see cref="IdsEmpresas"/>:
/// mismo criterio que <see cref="AltaArticulo"/>. <see cref="ControlaLote"/> (stage-12-lotes-
/// vencimientos, Slice 4, design: Reconciliation triggers): un flip <c>false → true</c>
/// dispara <c>ServicioDeLotes.ReconciliarAsync</c>; <c>ServicioDeArticulos.ActualizarAsync</c>
/// captura el valor previo ANTES de sobrescribir el campo para poder detectarlo.</summary>
public record EdicionArticulo(
    string Nombre,
    string? Descripcion,
    int IdArea,
    int? IdCategoria,
    int? IdMarca,
    int? IdGrupo,
    int? IdProveedorHabitual,
    int IdAlicuotaIva,
    UnidadVenta UnidadVenta,
    decimal? UnidadesPorBulto,
    bool EsProducto,
    decimal? CostoLista,
    decimal? DescuentoProveedor,
    decimal? CostoNominal,
    bool DisponibleParaTodas,
    IReadOnlyList<int>? IdsEmpresas,
    bool Activo,
    bool ControlaLote);

public record AltaCodigoBarra(string Codigo);

public record CodigoBarraListado(int Id, int IdArticulo, string Codigo, bool Activo);

/// <summary>Respuesta de <c>GET /api/articulos/{id}/sugerencia-precio</c> (spec: Margin-Based
/// Price Suggestion, "Suggestion requires explicit apply") — solo lectura, nunca persiste un
/// <c>precios</c> row por sí sola. <c>null</c> cuando no hay costo base o margen suficientes
/// para calcular una sugerencia (ver <see cref="Domain.Precios.SugeridorDePrecio.Sugerir"/>).</summary>
public record SugerenciaDePrecio(decimal? PrecioSugerido);

/// <summary>Fila de <c>GET /api/articulos/grilla</c> (back-office, grilla con filtros por
/// columna) — contrato DISTINTO de <see cref="ArticuloListado"/>: agrega <see cref="Precio"/>
/// (lista default del tenant) y <see cref="Proveedor"/> (etiqueta ya resuelta), que ese listado
/// no calcula, y omite el resto de los ~15 campos de edición que esta grilla no muestra.
/// <see cref="Precio"/> es <c>null</c> cuando el artículo no tiene un precio vigente resuelto en
/// la lista default (o cuando el tenant no tiene lista default, ver
/// <see cref="PaginaDeArticulosGrilla.NombreListaPrecio"/>). <see cref="Proveedor"/> es el
/// <c>NombreFantasia</c> del proveedor habitual cuando no es nulo/blanco, si no su
/// <c>RazonSocial</c> — <c>null</c> cuando el artículo no tiene proveedor habitual o el que
/// tiene es una fila invisible (baja lógica, FK colgante).</summary>
public record ArticuloGrillaFila(
    int Id,
    string CodigoInterno,
    string Nombre,
    decimal? Precio,
    int? IdProveedorHabitual,
    string? Proveedor,
    bool Activo);

/// <summary>Respuesta de <c>GET /api/articulos/grilla</c> — mismo shape que
/// <c>Usuarios.PaginaDe&lt;T&gt;</c> (<c>Items</c>/<c>Total</c>/<c>Pagina</c>/<c>Tamanio</c>)
/// más <see cref="NombreListaPrecio"/>, agregado como campo propio en vez de extender el genérico
/// compartido por más de una decena de listados — mismo criterio que
/// <c>Ventas.ContratosDeRemito.PaginaDeRemitos</c>/<c>Caja.Contratos.PaginaDeTurnos</c> (un
/// listado con una necesidad propia define su propio sobre, nunca modifica el contrato
/// compartido). <c>NombreListaPrecio</c> es el nombre de la lista default DEL TENANT (alcance
/// compartido, <c>id_empresa IS NULL</c> — esta grilla no tiene <c>idEmpresa</c>, a diferencia de
/// <c>GET /api/articulos</c>) a la que pertenece <see cref="ArticuloGrillaFila.Precio"/> de TODAS
/// las filas (para que el grid pueda titular la columna, p.ej. "Precio (General)"); <c>null</c>
/// cuando el tenant no tiene una lista default compartida — en ese caso el precio de cada fila
/// también es <c>null</c>, nunca se resuelve sin lista default.</summary>
public sealed record PaginaDeArticulosGrilla(
    IReadOnlyList<ArticuloGrillaFila> Items, int Total, int Pagina, int Tamanio, string? NombreListaPrecio);
