using Ways.Domain.Articulos;

namespace Ways.Application.Articulos;

/// <summary><see cref="IdsEmpresas"/> (judgment-day ronda 1, item 2) expone el subconjunto
/// ACTUAL de empresas del artículo — vacío cuando <see cref="DisponibleParaTodas"/> es
/// <c>true</c> — para que un cliente HTTP pueda armar un PUT de no-op (releer el detalle y
/// reenviarlo tal cual) sin perder el subset por mandar <c>null</c>. <c>ListarAsync</c> lo deja
/// vacío por fila (evita el N+1 de una query por artículo listado); el valor real solo se
/// completa en <c>ObtenerAsync</c>/<c>CrearAsync</c>/<c>ActualizarAsync</c>, que ya conocen o
/// resuelven el subset como parte de la operación.</summary>
public record ArticuloListado(
    int Id,
    string CodigoInterno,
    string Nombre,
    string? Descripcion,
    int IdArea,
    int? IdCategoria,
    int? IdMarca,
    int? IdGrupo,
    int? IdProveedorHabitual,
    int IdAlicuotaIva,
    UnidadVenta UnidadVenta,
    decimal? UnidadesPorBulto,
    bool EsProducto,
    decimal? CostoLista,
    decimal? DescuentoProveedor,
    decimal? CostoNominal,
    bool DisponibleParaTodas,
    IReadOnlyList<int> IdsEmpresas,
    bool Activo);

/// <summary><see cref="CodigoInterno"/> es opcional a propósito (spec: codigo_interno
/// Mandatory And Autogenerated) — cuando se omite, <c>ServicioDeArticulos.CrearAsync</c> lo
/// asigna desde <see cref="AsignadorDeCodigoInternoArticulo"/>; cuando se provee, se valida
/// único por tenant antes del INSERT. <see cref="IdsEmpresas"/> solo se usa cuando
/// <see cref="DisponibleParaTodas"/> es <c>false</c> (spec: Availability Model,
/// articulos_empresas Junction Schema) — se ignora en caso contrario.</summary>
public record AltaArticulo(
    string? CodigoInterno,
    string Nombre,
    string? Descripcion,
    int IdArea,
    int? IdCategoria,
    int? IdMarca,
    int? IdGrupo,
    int? IdProveedorHabitual,
    int IdAlicuotaIva,
    UnidadVenta UnidadVenta,
    decimal? UnidadesPorBulto,
    bool EsProducto,
    decimal? CostoLista,
    decimal? DescuentoProveedor,
    decimal? CostoNominal,
    bool DisponibleParaTodas = true,
    IReadOnlyList<int>? IdsEmpresas = null,
    bool Activo = true);

/// <summary><c>CodigoInterno</c> no aparece a propósito: no es editable por este ABM (mismo
/// criterio que <see cref="Ways.Application.Clientes.ClienteListado.Numero"/> — un valor
/// asignado en el alta, nunca tocado por una edición posterior). <see cref="IdsEmpresas"/>:
/// mismo criterio que <see cref="AltaArticulo"/>.</summary>
public record EdicionArticulo(
    string Nombre,
    string? Descripcion,
    int IdArea,
    int? IdCategoria,
    int? IdMarca,
    int? IdGrupo,
    int? IdProveedorHabitual,
    int IdAlicuotaIva,
    UnidadVenta UnidadVenta,
    decimal? UnidadesPorBulto,
    bool EsProducto,
    decimal? CostoLista,
    decimal? DescuentoProveedor,
    decimal? CostoNominal,
    bool DisponibleParaTodas,
    IReadOnlyList<int>? IdsEmpresas,
    bool Activo);

public record AltaCodigoBarra(string Codigo);

public record CodigoBarraListado(int Id, int IdArticulo, string Codigo, bool Activo);

/// <summary>Respuesta de <c>GET /api/articulos/{id}/sugerencia-precio</c> (spec: Margin-Based
/// Price Suggestion, "Suggestion requires explicit apply") — solo lectura, nunca persiste un
/// <c>precios</c> row por sí sola. <c>null</c> cuando no hay costo base o margen suficientes
/// para calcular una sugerencia (ver <see cref="Domain.Precios.SugeridorDePrecio.Sugerir"/>).</summary>
public record SugerenciaDePrecio(decimal? PrecioSugerido);
