using Ways.Application.Precios;
using Ways.Domain.Articulos;

namespace Ways.Application.Articulos;

/// <summary><see cref="IdsEmpresas"/> (judgment-day ronda 1, item 2) expone el subconjunto
/// ACTUAL de empresas del artículo — vacío cuando <see cref="DisponibleParaTodas"/> es
/// <c>true</c> — para que un cliente HTTP pueda armar un PUT de no-op (releer el detalle y
/// reenviarlo tal cual) sin perder el subset por mandar <c>null</c>. <c>ListarAsync</c> lo deja
/// vacío por fila (evita el N+1 de una query por artículo listado); el valor real solo se
/// completa en <c>ObtenerAsync</c>/<c>CrearAsync</c>/<c>ActualizarAsync</c>, que ya conocen o
/// resuelven el subset como parte de la operación. <see cref="CodigoProveedor"/> solo lo completa
/// <c>ListarAsync</c> cuando la búsqueda llegó con <c>idProveedor</c> y el artículo coincidió por
/// ese código; en cualquier otro caso (incluido el detalle) es <c>null</c>. <see cref="IdFamilia"/> es la
/// familia a la que pertenece el artículo (<c>null</c> = sin familia), tal como está guardada: no se anula
/// aunque la fila de la familia esté dada de baja, porque los escritores definen la pertenencia por esa
/// columna y por la baja del propio artículo (doc 10 §3, "Familias de artículos") — un lector que la
/// anulara y un escritor que la respetara discreparían sobre quién es miembro.</summary>
public record ArticuloListado(
    int Id,
    string CodigoInterno,
    string Nombre,
    string? Descripcion,
    int IdArea,
    int? IdCategoria,
    int? IdMarca,
    int? IdGrupo,
    int? IdProveedorHabitual,
    int IdAlicuotaIva,
    UnidadVenta UnidadVenta,
    decimal? UnidadesPorBulto,
    bool EsProducto,
    decimal? CostoLista,
    decimal? DescuentoProveedor,
    decimal? CostoNominal,
    bool DisponibleParaTodas,
    IReadOnlyList<int> IdsEmpresas,
    bool Activo,
    bool ControlaLote,
    bool AcumulaEnVenta,
    int? IdFamilia = null,
    string? CodigoProveedor = null);

/// <summary><see cref="CodigoInterno"/> es opcional a propósito (spec: codigo_interno
/// Mandatory And Autogenerated) — cuando se omite, <c>ServicioDeArticulos.CrearAsync</c> lo
/// asigna desde <see cref="AsignadorDeCodigoInternoArticulo"/>; cuando se provee, se valida
/// único por tenant antes del INSERT. <see cref="IdsEmpresas"/> solo se usa cuando
/// <see cref="DisponibleParaTodas"/> es <c>false</c> (spec: Availability Model,
/// articulos_empresas Junction Schema) — se ignora en caso contrario. <see cref="CodigoProveedor"/>
/// es el código que <see cref="IdProveedorHabitual"/> imprime en su factura: si viene no vacío
/// exige proveedor habitual y se persiste en la misma transacción que el artículo.
///
/// <para><see cref="IdFamilia"/> hace que el artículo nazca como miembro de esa familia (doc 10 §3). Entrar es un
/// cambio de pertenencia: el alta toma el lock de membresía exclusivo y, bajo él, exige que la familia
/// exista y esté viva (<c>404</c>), esté activa (<c>409 familia_inactiva</c>) y tenga al menos un artículo vivo
/// (<c>409 familia_sin_articulos</c>), y que los trece campos compartidos del pedido sean idénticos a los del
/// miembro vivo de menor id (<c>409 familia_valores_distintos</c>, que nombra las columnas que difieren). Entre
/// esos campos está <see cref="AcumulaEnVenta"/>: un pedido que no lo trae lleva su valor por defecto,
/// <c>true</c>, y se compara como cualquier otro. El artículo nace con el mismo estado de precios que ese
/// miembro en cada lista fija. Sin <see cref="IdFamilia"/> el artículo no pertenece a ninguna familia y el alta
/// no cambia.</para></summary>
public record AltaArticulo(
    string? CodigoInterno,
    string Nombre,
    string? Descripcion,
    int IdArea,
    int? IdCategoria,
    int? IdMarca,
    int? IdGrupo,
    int? IdProveedorHabitual,
    int IdAlicuotaIva,
    UnidadVenta UnidadVenta,
    decimal? UnidadesPorBulto,
    bool EsProducto,
    decimal? CostoLista,
    decimal? DescuentoProveedor,
    decimal? CostoNominal,
    bool DisponibleParaTodas = true,
    IReadOnlyList<int>? IdsEmpresas = null,
    bool Activo = true,
    bool ControlaLote = false,
    string? CodigoProveedor = null,
    bool AcumulaEnVenta = true,
    int? IdFamilia = null);

/// <summary><c>CodigoInterno</c> no aparece a propósito: no es editable por este ABM (mismo
/// criterio que <see cref="Ways.Application.Clientes.ClienteListado.Numero"/> — un valor
/// asignado en el alta, nunca tocado por una edición posterior). <see cref="IdsEmpresas"/>:
/// mismo criterio que <see cref="AltaArticulo"/>. <see cref="ControlaLote"/> (stage-12-lotes-
/// vencimientos, Slice 4, design: Reconciliation triggers): un flip <c>false → true</c>
/// dispara <c>ServicioDeLotes.ReconciliarAsync</c>; <c>ServicioDeArticulos.ActualizarAsync</c>
/// captura el valor previo ANTES de sobrescribir el campo para poder detectarlo.
/// <see cref="AcumulaEnVenta"/> <c>null</c> deja el valor guardado como está: un cliente que no conoce
/// el campo no debe pisar un <c>false</c> con el default.
///
/// <para><see cref="Alcance"/> es la decisión del cliente cuando el artículo pertenece a una familia
/// (doc 10 §3) y la edición cambia alguno de sus trece campos compartidos
/// (<see cref="ValoresCompartidosDeFamilia"/>); cada valor tiene un destino. Sobre un artículo sin familia,
/// <c>null</c> lo edita solo. Sobre un miembro, <c>null</c> con un cambio compartido se rechaza con
/// <c>alcance_requerido</c> (409) sin escribir nada, y <c>null</c> sin cambio compartido escribe solo los
/// campos propios del artículo (no hay nada que replicar).
/// <see cref="AlcanceDeFamilia.Familia"/> aplica los trece campos compartidos del pedido a todos los miembros
/// vivos y los campos propios solo al artículo editado (sin cambio compartido no hay nada que replicar y se
/// escriben solo los propios). <see cref="AlcanceDeFamilia.SoloEste"/> saca al artículo de la familia, haya o
/// no cambio compartido, y escribe todo solo en él. Un <see cref="Alcance"/> explícito sobre un artículo que
/// no es miembro se rechaza con <c>familia_cambio</c> (409). Un ordinal que no es el de ninguno de los dos
/// valores (el JSON del servidor acepta el ordinal además del nombre; <c>0</c> incluido) llega al servicio y
/// se rechaza con <c>alcance_invalido</c> (400); un texto que no se lee ni como nombre ni como ordinal no
/// llega al servicio y lo rechaza el binding JSON del framework. Con <see cref="AcumulaEnVenta"/>
/// <c>null</c> el valor del pedido para ese campo compartido es el guardado en el artículo editado: no
/// cuenta como cambio y, con <c>Familia</c>, es el que se aplica a todos los miembros vivos.</para></summary>
public record EdicionArticulo(
    string Nombre,
    string? Descripcion,
    int IdArea,
    int? IdCategoria,
    int? IdMarca,
    int? IdGrupo,
    int? IdProveedorHabitual,
    int IdAlicuotaIva,
    UnidadVenta UnidadVenta,
    decimal? UnidadesPorBulto,
    bool EsProducto,
    decimal? CostoLista,
    decimal? DescuentoProveedor,
    decimal? CostoNominal,
    bool DisponibleParaTodas,
    IReadOnlyList<int>? IdsEmpresas,
    bool Activo,
    bool ControlaLote,
    bool? AcumulaEnVenta = null,
    AlcanceDeFamilia? Alcance = null);

public record AltaCodigoBarra(string Codigo);

public record CodigoBarraListado(int Id, int IdArticulo, string Codigo, bool Activo);

public record AltaCodigoProveedor(int IdProveedor, string Codigo);

public record CodigoProveedorListado(int IdCodigoProveedor, int IdArticulo, int IdProveedor, string Codigo);

/// <summary><see cref="Creado"/> distingue el alta nueva (201) de la asociación idempotente de un
/// código que ya estaba activo en el mismo artículo (200).</summary>
public record ResultadoDeCodigoProveedor(CodigoProveedorListado Codigo, bool Creado);

/// <summary>Respuesta de <c>GET /api/articulos/{id}/sugerencia-precio</c> (spec: Margin-Based
/// Price Suggestion, "Suggestion requires explicit apply") — solo lectura, nunca persiste un
/// <c>precios</c> row por sí sola. <c>null</c> cuando no hay costo base o margen suficientes
/// para calcular una sugerencia (ver <see cref="Domain.Precios.SugeridorDePrecio.Sugerir"/>).</summary>
public record SugerenciaDePrecio(decimal? PrecioSugerido);

/// <summary>Fila de <c>GET /api/articulos/grilla</c> (back-office, grilla con filtros por
/// columna) — contrato DISTINTO de <see cref="ArticuloListado"/>: agrega <see cref="Precio"/>
/// (lista default del tenant) y <see cref="Proveedor"/> (etiqueta ya resuelta), que ese listado
/// no calcula, y omite el resto de los ~15 campos de edición que esta grilla no muestra.
/// <see cref="Precio"/> es <c>null</c> cuando el artículo no tiene un precio vigente resuelto en
/// la lista default (o cuando el tenant no tiene lista default, ver
/// <see cref="PaginaDeArticulosGrilla.NombreListaPrecio"/>). <see cref="IdProveedorHabitual"/> y
/// <see cref="Proveedor"/> viajan juntos: ambos <c>null</c> cuando el artículo no tiene proveedor
/// habitual O el que tiene es una fila invisible (baja lógica, FK colgante) — un id colgante
/// nunca se expone (mismo criterio que los filtros <c>idProveedor</c>/<c>sinProveedor</c> del
/// servicio, que tampoco lo matchean/lo tratan como "sin proveedor"). <see cref="Proveedor"/> es
/// el <c>NombreFantasia</c> del proveedor habitual cuando no es nulo/blanco, si no su
/// <c>RazonSocial</c>. <see cref="CostoNominal"/> es el costo real de reposición y solo lo reciben
/// admin y supervisor; para el vendedor viaja <c>null</c>, igual que un artículo sin costo cargado.</summary>
public record ArticuloGrillaFila(
    int Id,
    string CodigoInterno,
    string Nombre,
    decimal? Precio,
    decimal? CostoNominal,
    int? IdProveedorHabitual,
    string? Proveedor,
    bool Activo);

/// <summary>Respuesta de <c>GET /api/articulos/grilla</c> — mismo shape que
/// <c>Usuarios.PaginaDe&lt;T&gt;</c> (<c>Items</c>/<c>Total</c>/<c>Pagina</c>/<c>Tamanio</c>)
/// más <see cref="NombreListaPrecio"/>, agregado como campo propio en vez de extender el genérico
/// compartido por más de una decena de listados — mismo criterio que
/// <c>Ventas.ContratosDeRemito.PaginaDeRemitos</c>/<c>Caja.Contratos.PaginaDeTurnos</c> (un
/// listado con una necesidad propia define su propio sobre, nunca modifica el contrato
/// compartido). <c>NombreListaPrecio</c> es el nombre de la lista default DEL TENANT (alcance
/// compartido, <c>id_empresa IS NULL</c> — esta grilla no tiene <c>idEmpresa</c>, a diferencia de
/// <c>GET /api/articulos</c>) a la que pertenece <see cref="ArticuloGrillaFila.Precio"/> de TODAS
/// las filas (para que el grid pueda titular la columna, p.ej. "Precio (General)"); <c>null</c>
/// cuando el tenant no tiene una lista default compartida — en ese caso el precio de cada fila
/// también es <c>null</c>, nunca se resuelve sin lista default.</summary>
public sealed record PaginaDeArticulosGrilla(
    IReadOnlyList<ArticuloGrillaFila> Items, int Total, int Pagina, int Tamanio, string? NombreListaPrecio);
